/* Auto-generated by LLM (reharness) */
#![cfg_attr(not(test), no_std)]

use core::ptr::{read_volatile, write_volatile};

pub const IO_ID: usize = 0x00;
pub const IO_IRQ_STATUS: usize = 0x24;
pub const IO_IRQ_ACK: usize = 0x64;

#[repr(C)]
pub struct Edu {
    pub base: usize,
}

impl Edu {
    pub fn init(base: usize) -> Self {
        Self { base }
    }

    #[inline]
    pub unsafe fn read_reg(&self, offset: usize) -> u32 {
        read_volatile((self.base + offset) as *const u32)
    }

    #[inline]
    pub unsafe fn write_reg(&self, offset: usize, value: u32) {
        write_volatile((self.base + offset) as *mut u32, value);
    }

    #[inline]
    pub unsafe fn read_reg8(&self, offset: usize) -> u8 {
        read_volatile((self.base + offset) as *const u8)
    }

    #[inline]
    pub unsafe fn write_reg8(&self, offset: usize, value: u8) {
        write_volatile((self.base + offset) as *mut u8, value);
    }

    #[inline]
    pub unsafe fn read_reg16(&self, offset: usize) -> u16 {
        read_volatile((self.base + offset) as *const u16)
    }

    #[inline]
    pub unsafe fn write_reg16(&self, offset: usize, value: u16) {
        write_volatile((self.base + offset) as *mut u16, value);
    }

    #[inline]
    pub unsafe fn read_reg16be(&self, offset: usize) -> u16 {
        u16::from_be(read_volatile((self.base + offset) as *const u16))
    }

    #[inline]
    pub unsafe fn write_reg16be(&self, offset: usize, value: u16) {
        write_volatile((self.base + offset) as *mut u16, value.to_be());
    }

    #[inline]
    pub unsafe fn read_reg32be(&self, offset: usize) -> u32 {
        u32::from_be(read_volatile((self.base + offset) as *const u32))
    }

    #[inline]
    pub unsafe fn write_reg32be(&self, offset: usize, value: u32) {
        write_volatile((self.base + offset) as *mut u32, value.to_be());
    }

    #[inline]
    pub unsafe fn write_reg_w1c8(&self, offset: usize, value: u8) {
        let cur = self.read_reg8(offset);
        self.write_reg8(offset, cur & !value);
    }

    #[inline]
    pub unsafe fn write_reg_w1c16(&self, offset: usize, value: u16) {
        let cur = self.read_reg16(offset);
        self.write_reg16(offset, cur & !value);
    }

    #[inline]
    pub unsafe fn write_reg_w1c32(&self, offset: usize, value: u32) {
        let cur = self.read_reg(offset);
        self.write_reg(offset, cur & !value);
    }

    pub unsafe fn edu_irq_handler(&self) {
        let status = self.read_reg(IO_IRQ_STATUS);
        self.write_reg(IO_IRQ_ACK, status);
    }

    pub unsafe fn edu_read(&self) -> u32 {
        self.read_reg(0x0)
    }

    pub unsafe fn edu_write(&self, val: u32) {
        self.write_reg(0x0, val);
    }

    pub unsafe fn edu_pci_probe(&self, mmio: usize, ret: u32) -> u32 {
        if mmio != 0x0 {
            if ret == 0x0 {
                let _dev_id = self.read_reg(IO_ID);
            }
        }
        ret
    }
}