#ifndef REHARNESS_EDU_BAREMETAL_H
#define REHARNESS_EDU_BAREMETAL_H

/* Auto-generated by LLM (reharness) */
#ifndef EDU_DRIVER_H
#define EDU_DRIVER_H

#include <stdint.h>

/* Register Offsets */
#define IO_ID          0x00
#define IO_IRQ_STATUS  0x24
#define IO_IRQ_ACK     0x64

/* Device Private Structure */
struct edu_priv {
    uintptr_t base;
    uintptr_t mmio;
};

#endif /* REHARNESS_EDU_BAREMETAL_H */
