#ifndef REHARNESS_EDU_LINUX_H
#define REHARNESS_EDU_LINUX_H

/* Auto-generated by LLM (reharness) */
#include <linux/module.h>
#include <linux/io.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/miscdevice.h>
#include <linux/slab.h>
#include <linux/err.h>
#include <linux/pci.h>

/* Constants */
#define DMA_BASE 262144
#define DMA_CMD 1
#define DMA_IRQ 4
#define EDU_DEVICE_ID 4584
#define EDU_VENDOR_ID 4660
#define IO_APIC_DEFAULT_PHYS_BASE 4273995776
#define IO_APIC_SLOT_SIZE 1024
#define IO_BITMAP_BITS 65536
#define IO_DMA_CMD 152
#define IO_DMA_CNT 144
#define IO_DMA_DST 136
#define IO_DMA_SRC 128
#define IO_INTEGRITY_CHK_APPTAG 4
#define IO_INTEGRITY_CHK_GUARD 1
#define IO_INTEGRITY_CHK_REFTAG 2
#define IO_SPACE_LIMIT 65535

/* Registers */
#define IO_ID 0
#define IO_IRQ_ACK 100
#define IO_IRQ_STATUS 36

/* MMIO trace instrumentation */
static void __iomem *__rh_mmio_base;
#define RH_SET_BASE(b) do { __rh_mmio_base = (b); pr_info("[rhbase] %px\n", (void __iomem *)(b)); } while (0)
#define RH_TRACE_FN(name) pr_info("[rhfn] %s\n", (name))
#define rh_off(p) ((unsigned long)((const void __iomem *)(p) - __rh_mmio_base))
#undef readl
#define readl(p) ({ u32 __v = __raw_readl(p); pr_info("[rh] R 0x%lx 0x%x\n", rh_off(p), __v); __v; })
#undef writel
#define writel(v,p) ({ pr_info("[rh] W 0x%lx 0x%x\n", rh_off(p), (u32)(v)); __raw_writel((v),(p)); })

struct edu_priv {
    int irq;
    struct miscdevice mdev;
    void __iomem *mmio;
    struct pci_dev *pdev;
    struct device *dev;
};

#endif /* REHARNESS_EDU_LINUX_H */
