/* Auto-generated by LLM (reharness) */
#![cfg_attr(not(test), no_std)]

// tock-registers re-exports (inline minimal subset if crate is unavailable)
#[cfg(not(feature = "tock-registers"))]
mod tock_registers {
    use core::ptr::{read_volatile, write_volatile};
    pub trait RegisterLongName {}
    pub struct LocalRegisterCopy<T, R: RegisterLongName> { value: T, _reg: core::marker::PhantomData<R> }
    impl<T: Copy, R: RegisterLongName> LocalRegisterCopy<T, R> {
        pub fn new(v: T) -> Self { Self { value: v, _reg: core::marker::PhantomData } }
        pub fn get(&self) -> T { self.value }
    }
    pub struct ReadWrite<T: Copy, R: RegisterLongName> { address: *mut T, _reg: core::marker::PhantomData<R> }
    impl<T: Copy + core::ops::BitAnd<Output = T> + core::ops::BitOr<Output = T> + core::ops::Not<Output = T>, R: RegisterLongName> ReadWrite<T, R> {
        pub const fn new(addr: *mut T) -> Self { Self { address: addr, _reg: core::marker::PhantomData } }
        pub fn get(&self) -> T { unsafe { read_volatile(self.address) } }
        pub fn set(&self, value: T) { unsafe { write_volatile(self.address, value) } }
        pub fn read(&self) -> LocalRegisterCopy<T, R> { LocalRegisterCopy::new(self.get()) }
        pub fn write(&self, field: LocalRegisterCopy<T, R>) { self.set(field.get()); }
    }
    pub struct ReadOnly<T: Copy, R: RegisterLongName> { address: *const T, _reg: core::marker::PhantomData<R> }
    impl<T: Copy, R: RegisterLongName> ReadOnly<T, R> {
        pub const fn new(addr: *const T) -> Self { Self { address: addr, _reg: core::marker::PhantomData } }
        pub fn get(&self) -> T { unsafe { read_volatile(self.address) } }
        pub fn read(&self) -> LocalRegisterCopy<T, R> { LocalRegisterCopy::new(self.get()) }
    }
    pub struct WriteOnly<T: Copy, R: RegisterLongName> { address: *mut T, _reg: core::marker::PhantomData<R> }
    impl<T: Copy, R: RegisterLongName> WriteOnly<T, R> {
        pub const fn new(addr: *mut T) -> Self { Self { address: addr, _reg: core::marker::PhantomData } }
        pub fn set(&self, value: T) { unsafe { write_volatile(self.address, value) } }
    }
}
#[cfg(feature = "tock-registers")]
use tock_registers::{
    registers::{ReadWrite, ReadOnly, WriteOnly, LocalRegisterCopy},
    register_bitfields,
};

use tock_registers::registers::{ReadOnly, WriteOnly};
use tock_registers::RegisterLongName;

struct IoId; impl RegisterLongName for IoId {}
struct IoIrqStatus; impl RegisterLongName for IoIrqStatus {}
struct IoIrqAck; impl RegisterLongName for IoIrqAck {}

#[repr(C)]
pub struct EduRegisters {
    pub id: ReadOnly<u32, IoId>,                 // offset 0x00
    _reserved0: [u8; 0x24 - 0x04],               // padding to 0x24
    pub irq_status: ReadOnly<u32, IoIrqStatus>,  // offset 0x24
    _reserved1: [u8; 0x64 - 0x28],               // padding to 0x64
    pub irq_ack: WriteOnly<u32, IoIrqAck>,       // offset 0x64
}

pub struct Edu {
    regs: &'static EduRegisters,
}

impl Edu {
    pub fn new(base: *mut u8) -> Self {
        Self {
            regs: unsafe { &*(base as *const EduRegisters) },
        }
    }

    pub fn edu_irq_handler(&self) {
        let status = self.regs.irq_status.read().get();
        self.regs.irq_ack.set(status);
    }

    pub fn edu_read(&self) -> u32 {
        let val = self.regs.id.read().get();
        val
    }

    pub fn edu_write(&self, val: u32) {
        self.regs.id.set(val);
    }

    pub fn edu_pci_probe(&self, priv_mmio: u32, ret: u32) -> u32 {
        let mut dev_id: u32 = 0;
        if priv_mmio == 0x0 {
            if ret == 0x0 {
                dev_id = self.regs.id.read().get();
            }
        }
        dev_id
    }
}