/* Auto-generated by LLM (reharness) */
#![cfg_attr(not(test), no_std)]

use tock_registers::{
    register_bitfields,
    register_structs,
    registers::{ReadOnly, ReadWrite, WriteOnly},
};

register_structs! {
    pub EduRegisters {
        (0x000 => id: ReadOnly<u32, IdReg::Register>),
        (0x004 => _reserved0),
        (0x024 => irq_status: ReadOnly<u32, IrqStatus::Register>),
        (0x028 => _reserved1),
        (0x064 => irq_ack: WriteOnly<u32, IrqAck::Register>),
        (0x068 => @END),
    }
}

register_bitfields![u32,
    IdReg [],
    IrqStatus [],
    IrqAck [],
    Value [],
]

pub struct Edu {
    regs: &'static EduRegisters,
}

impl Edu {
    pub fn new(base: *mut u8) -> Self {
        Self {
            regs: unsafe { &*(base as *const EduRegisters) },
        }
    }

    pub fn edu_irq_handler(&self) {
        let status = self.regs.irq_status.get();
        self.regs.irq_ack.set(status);
    }

    pub fn edu_read(&self) -> u32 {
        let val = self.regs.id.get();
        val
    }

    pub fn edu_write(&self, val: u32) {
        self.regs.id.set(val);
    }

    pub fn edu_pci_probe(&self, priv_mmio: u32, ret: u32) -> Option<u32> {
        if priv_mmio != 0x0 {
            return None;
        }
        if ret != 0x0 {
            return None;
        }
        let dev_id = self.regs.id.get();
        Some(dev_id)
    }
}