#ifndef REHARNESS_DW_APB_SSI_LINUX_H
#define REHARNESS_DW_APB_SSI_LINUX_H

/* Auto-generated by LLM (reharness), 4 chunked parts */
/* ---- part 00 of 03 ---- */
#include <linux/module.h>
#include <linux/io.h>
#include <linux/platform_device.h>
#include <linux/spi/spi.h>
#include <linux/spi/spi-mem.h>
#include <linux/interrupt.h>
#include <linux/clk.h>
#include <linux/reset.h>
#include <linux/regmap.h>
#include <linux/of.h>
#include <linux/pm.h>
#include <linux/slab.h>
#include <linux/err.h>

/* =============================================================================
 * Register offset constants
 * =============================================================================
 */
#define DW_SPI_CTRLR0		0x00
#define DW_SPI_CTRLR1		0x04
#define DW_SPI_SSIENR		0x08
#define DW_SPI_MWCR		0x0C
#define DW_SPI_SER		0x10
#define DW_SPI_BAUDR		0x14
#define DW_SPI_TXFTLR		0x18
#define DW_SPI_RXFTLR		0x1C
#define DW_SPI_TXFLR		0x20
#define DW_SPI_RXFLR		0x24
#define DW_SPI_SR		0x28
#define DW_SPI_IMR		0x2C
#define DW_SPI_ISR		0x30
#define DW_SPI_RISR		0x34
#define DW_SPI_TXOICR		0x38
#define DW_SPI_RXOICR		0x3C
#define DW_SPI_RXUICR		0x40
#define DW_SPI_MSTICR		0x44
#define DW_SPI_ICR		0x48
#define DW_SPI_DMACR		0x4C
#define DW_SPI_DMATDLR		0x50
#define DW_SPI_DMARDLR		0x54
#define DW_SPI_IDR		0x58
#define DW_SPI_VERSION		0x5C
#define DW_SPI_DR		0x60
#define DW_SPI_RX_SAMPLE_DLY	0xF0
#define DW_SPI_CS_OVERRIDE	0xF4
#define MSCC_SPI_MST_SW_MODE	0x14

/* =============================================================================
 * Protocol/format bit constants
 * =============================================================================
 */
#define DW_SPI_CTRLR0_TMOD_TR		0
#define DW_SPI_CTRLR0_TMOD_TO		1
#define DW_SPI_CTRLR0_TMOD_RO		2
#define DW_SPI_CTRLR0_TMOD_EPROMREAD	3
#define DW_SPI_CTRLR0_FRF_MOTO_SPI	0
#define DW_SPI_CTRLR0_FRF_TI_SSP	1
#define DW_SPI_CTRLR0_FRF_NS_MICROWIRE	2
#define DW_SPI_CTRLR0_FRF_RESV		3

/* =============================================================================
 * Interrupt mask/status bits
 * =============================================================================
 */
#define DW_SPI_INT_TXEI		0x01
#define DW_SPI_INT_TXOI		0x02
#define DW_SPI_INT_RXUI		0x04
#define DW_SPI_INT_RXOI		0x08
#define DW_SPI_INT_RXFI		0x10
#define DW_SPI_INT_MSTI		0x20

/* =============================================================================
 * Status register bits
 * =============================================================================
 */
#define DW_SPI_SR_TF_EMPT		0x04
#define DW_SPI_SR_TF_NOT_FULL		0x02
#define DW_SPI_SR_RF_NOT_EMPT		0x08
#define DW_SPI_SR_RF_FULL		0x10
#define DW_SPI_SR_TX_ERR		0x20
#define DW_SPI_SR_DCOL		0x40
#define DW_SPI_SR_BUSY		0x01

/* =============================================================================
 * FIFO / DMA constants
 * ============================================================================= */
#define DW_SPI_DMACR_RDMAE	0x01
#define DW_SPI_DMACR_TDMAE	0x02
#define DW_SPI_WAIT_RETRIES	5
#define DW_SPI_CAP_CS_OVERRIDE	1
#define DW_SPI_CAP_DFS32	2

/* =============================================================================
 * PSSI (APB SSI) CTRLR0 bits
 * =============================================================================
 */
#define DW_PSSI_CTRLR0_SCPHA		64
#define DW_PSSI_CTRLR0_SCPOL		128
#define DW_PSSI_CTRLR0_SRL		2048
#define DW_PSSI_CTRLR0_CFS		4096
#define DW_PSSI_CTRLR0_SLV_OE		1024
#define DW_PSSI_ID		0

/* =============================================================================
 * HSSI (High-Speed SSI) CTRLR0 bits
 * =============================================================================
 */
#define DW_HSSI_CTRLR0_MST		2147483648
#define DW_HSSI_CTRLR0_SCPHA		256
#define DW_HSSI_CTRLR0_SCPOL		512
#define DW_HSSI_CTRLR0_SRL		8192
#define DW_HSSI_ID		1
#define DW_HSSI_102A		825242154

/* =============================================================================
 * MSCC / Vitesse constants
 * =============================================================================
 */
#define MSCC_IF_SI_OWNER_SISL		0
#define MSCC_IF_SI_OWNER_SIBM		1
#define MSCC_IF_SI_OWNER_SIMC		2
#define MSCC_CPU_SYSTEM_CTRL_GENERAL_CTRL	36
#define MSCC_SPI_MST_SW_MODE_SW_PIN_CTRL_MODE	8192
#define OCELOT_IF_SI_OWNER_OFFSET		4
#define JAGUAR2_IF_SI_OWNER_OFFSET	6

/* =============================================================================
 * Sparx5 constants
 * =============================================================================
 */
#define SPARX5_FORCE_ENA	164
#define SPARX5_FORCE_VAL	168

/* =============================================================================
 * Elba constants
 * =============================================================================
 */
#define ELBA_SPICS_REG		9320

/* =============================================================================
 * Helper macros for bus width
 * =============================================================================
 */
#define dw_readl(priv, reg)		readl((priv)->base + (reg))
#define dw_writel(priv, reg, val)	writel((val), (priv)->base + (reg))
#define dw_readw(priv, reg)		readw((priv)->base + (reg))
#define dw_writew(priv, reg, val)	writew((val), (priv)->base + (reg))

/* =============================================================================
 * Upstream struct definitions (minimal for harness compilation)
 * =============================================================================
 */

struct dw_spi_chip_data {
	u32 cr0;
	u32 rx_sample_dly;
};

#endif /* REHARNESS_DW_APB_SSI_LINUX_H */
