#ifndef REHARNESS_DW-APB-SSI_LINUX_H
#define REHARNESS_DW-APB-SSI_LINUX_H

/* Auto-generated by LLM (reharness) */
#include <linux/module.h>
#include <linux/io.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/miscdevice.h>
#include <linux/slab.h>
#include <linux/err.h>
#include <linux/platform_device.h>

static void __iomem *__rh_mmio_base;
#define RH_SET_BASE(b) do { __rh_mmio_base = (b); pr_info("[rhbase] %px\n", (void __iomem *)(b)); } while (0)
#define RH_TRACE_FN(name) pr_info("[rhfn] %s\n", (name))
#define rh_off(p) ((unsigned long)((const void __iomem *)(p) - __rh_mmio_base))
#undef readl
#define readl(p) ({ u32 __v = __raw_readl(p); pr_info("[rh] R 0x%lx 0x%x\n", rh_off(p), __v); __v; })
#undef writel
#define writel(v,p) ({ pr_info("[rh] W 0x%lx 0x%x\n", rh_off(p), (u32)(v)); __raw_writel((v),(p)); })

#define DW_SPI_CTRLR0                 0x00
#define DW_SPI_CTRLR1                 0x04
#define DW_SPI_SER                    0x10
#define MSCC_SPI_MST_SW_MODE          0x14
#define DW_SPI_TXFTLR                 0x18
#define DW_SPI_RXFTLR                 0x1c
#define DW_SPI_TXFLR                  0x20
#define DW_SPI_RXFLR                  0x24
#define DW_SPI_SR                     0x28
#define DW_SPI_ISR                    0x30
#define DW_SPI_RISR                   0x34
#define DW_SPI_VERSION                0x5c
#define DW_SPI_RX_SAMPLE_DLY          0xf0
#define DW_SPI_CS_OVERRIDE            0xf4

#define DW_SPI_CAP_CS_OVERRIDE        1
#define DW_SPI_CAP_DFS32              2
#define DW_SPI_CTRLR0_TMOD_EPROMREAD  3
#define DW_SPI_CTRLR0_TMOD_RO         2
#define DW_SPI_INT_TXEI               1
#define IRQ_NOTCONNECTED              2147483648

struct dw_apb_ssi_priv {
	void __iomem *base;
	struct miscdevice misc;
	struct device *dev;
};

#endif /* REHARNESS_DW-APB-SSI_LINUX_H */
