#ifndef REHARNESS_DW_APB_SSI_BAREMETAL_H
#define REHARNESS_DW_APB_SSI_BAREMETAL_H

/* Auto-generated by LLM (reharness) */
#ifndef DW_APB_SSI_H
#define DW_APB_SSI_H

#include <stdint.h>

/* Register Offsets */
#define DW_SPI_CTRLR0           0x00
#define DW_SPI_CTRLR1           0x04
#define DW_SPI_SSIENR           0x08
#define DW_SPI_SER              0x10
#define DW_SPI_BAUDR            0x14
#define MSCC_SPI_MST_SW_MODE    0x14
#define DW_SPI_TXFTLR           0x18
#define DW_SPI_RXFTLR           0x1C
#define DW_SPI_TXFLR            0x20
#define DW_SPI_RXFLR            0x24
#define DW_SPI_SR               0x28
#define DW_SPI_IMR              0x2C
#define DW_SPI_ISR              0x30
#define DW_SPI_RISR             0x34
#define DW_SPI_ICR              0x48
#define DW_SPI_DR               0x60
#define DW_SPI_VERSION          0x5C
#define DW_SPI_RX_SAMPLE_DLY    0xF0
#define DW_SPI_CS_OVERRIDE      0xF4

/* Constants */
#define DW_SPI_INT_TXEI         0x00000001
#define DW_SPI_CTRLR0_TMOD_EPROMREAD 0x0
#define DW_SPI_CTRLR0_TMOD_RO   0x0
#define DW_SPI_CAP_CS_OVERRIDE  0x1
#define IRQ_NOTCONNECTED        0xFFFFFFFF
#define EPROBE_DEFER            517
#define ENOTCONN                107

/* Primitives */
static inline uint32_t mmio_read32(uintptr_t addr) {
    return *(volatile uint32_t *)addr;
}

static inline void mmio_write32(uint32_t value, uintptr_t addr) {
    *(volatile uint32_t *)addr = value;
}

/* Device Structures */
struct dw_apb_ssi_priv {
    uintptr_t base;
    uint32_t chip_select[4];
    uint32_t ver;
    uint32_t num_cs;
    uint32_t fifo_len;
    uint32_t caps;
    uint32_t current_freq;
    uint32_t cur_rx_sample_dly;
    uint32_t irq;
    uint32_t dma_mapped;
    uint32_t n_bytes;
    uint32_t rx_len;
    uint32_t tx_len;
    void *tx;
    void *rx;
    void *ctlr;
    void *cur_msg;
    void *dma_ops;
};

#endif /* REHARNESS_DW_APB_SSI_BAREMETAL_H */
