#ifndef REHARNESS_SPI-DW-CORE_HARNESS_H
#define REHARNESS_SPI-DW-CORE_HARNESS_H

/* Auto-generated by LLM (reharness) */
#include <stdint.h>
#include <stdio.h>

/* Kernel macro stubs */
#define BIT(n)              (1UL << (n))
#define GENMASK(h, l)       (((1UL << ((h) - (l) + 1)) - 1) << (l))
#define DW_SPI_CTRLR0_TMOD_EPROMREAD 0x2
#define DW_SPI_CTRLR0_TMOD_RO        0x0
#define DW_SPI_CAP_CS_OVERRIDE       0x1

/* Register Offsets */
#define DW_SPI_CTRLR0         0x000
#define DW_SPI_CTRLR1         0x004
#define DW_SPI_SER            0x010
#define DW_SPI_TXFTLR         0x018
#define DW_SPI_RXFTLR         0x01C
#define DW_SPI_TXFLR          0x020
#define DW_SPI_RXFLR          0x024
#define DW_SPI_SR             0x028
#define DW_SPI_ISR            0x030
#define DW_SPI_RISR           0x034
#define DW_SPI_VERSION        0x05C
#define DW_SPI_RX_SAMPLE_DLY  0x0F0
#define DW_SPI_CS_OVERRIDE    0x0F4

static unsigned long trace_count = 0;

/* Primitive stubs */
uint8_t harness_read8(uintptr_t addr) {
    uint8_t value = 0;
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
    return value;
}

uint16_t harness_read16(uintptr_t addr) {
    uint16_t value = 0;
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
    return value;
}

uint32_t harness_read32(uintptr_t addr) {
    uint32_t value = 0;
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
    return value;
}

uint16_t harness_read16be(uintptr_t addr) {
    uint16_t value = 0;
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
    return value;
}

uint32_t harness_read32be(uintptr_t addr) {
    uint32_t value = 0;
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
    return value;
}

void harness_write8(uint8_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write16(uint16_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write32(uint32_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write16be(uint16_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write32be(uint32_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write_w1c8(uint8_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write_w1c16(uint16_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

void harness_write_w1c32(uint32_t value, uintptr_t addr) {
    printf("[trace %lu] R/W 0x%03lx = 0x%08x\n", trace_count++, (unsigned long)addr, value);
}

/* Device private struct */
struct spi_dw_core_priv {
    uintptr_t base;
    uint32_t ver;
    uint32_t num_cs;
    uint32_t fifo_len;
    uint32_t caps;
    uint32_t rx_len;
    uint32_t cur_rx_sample_dly;
    uintptr_t regs;
};

#endif /* REHARNESS_SPI-DW-CORE_HARNESS_H */
