/* Auto-generated by LLM (reharness), 4 chunked parts */
/* ---- part 00 of 03 ---- */
//! DW APB SSI (DesignWare APB SSI) SPI Controller Driver
//!
//! This is the scaffold (part 0 of 4) containing register definitions,
//! driver struct, constructor, and method prototypes.

#![cfg_attr(not(test), no_std)]

use tock_registers::{
    register_bitfields,
    register_structs,
    registers::{ReadOnly, ReadWrite, WriteOnly},
};

// ---------------------------------------------------------------------------
// Register bitfield definitions
// ---------------------------------------------------------------------------
register_bitfields![u32,
Ctrlr0 [
        /// Data frame size: 0=2-bit .. 15=16-bit (DSCR field, 4 bits)
        DFS     OFFSET(0)  NUMBITS(4),
        /// Frame format: 0=Moto SPI, 1=Texas SSP, 2=Nat MicroWire, 3=Reserved
        FRF     OFFSET(4)  NUMBITS(2),
        /// SPI mode (clock polarity/phase)
        SCPH    OFFSET(6)  NUMBITS(1),
        /// Serial clock polarity
        SCPOL   OFFSET(7)  NUMBITS(1),
        /// Serial frame mode
        TMOD    OFFSET(8)  NUMBITS(2),
        /// Slave mode enable
        SLV_OE  OFFSET(10) NUMBITS(1),
        /// Management reference clock divider
        MDMA    OFFSET(11) NUMBITS(1),
        /// Instantaneous data frame size
        SPI_3WIRE_MODE OFFSET(15) NUMBITS(1),
        /// Data frame size extension (16-32 bit)
        DFS_32  OFFSET(16) NUMBITS(16),
    ],
    Ctrlr1 [
        /// Number of data frames to receive or transmit
        NDF OFFSET(0) NUMBITS(16),
    ],
    Ssienr [
        /// SSI enable
        SSI_EN OFFSET(0) NUMBITS(1),
    ],
    Ser [
        /// Slave select enable for each CS
        SSR OFFSET(0) NUMBITS(16),
    ],
    Baudr [
        /// Clock divider
        SCKDV OFFSET(0) NUMBITS(16),
    ],
    Txftlr [
        /// TX FIFO threshold
        TFT OFFSET(0) NUMBITS(8),
    ],
    Rxftlr [
        /// RX FIFO threshold
        RFT OFFSET(0) NUMBITS(8),
    ],
    Txflr [
        /// TX FIFO level
        TFTFL OFFSET(0) NUMBITS(8),
    ],
    Rxflr [
        /// RX FIFO level
        RXTFL OFFSET(0) NUMBITS(8),
    ],
    Sr [
        /// TX FIFO not full
        TFNF OFFSET(1) NUMBITS(1),
        /// TX FIFO empty
        TFE  OFFSET(2) NUMBITS(1),
        /// RX FIFO not empty
        RFNE OFFSET(3) NUMBITS(1),
        /// RX FIFO full
        RFF  OFFSET(4) NUMBITS(1),
        /// SSI busy
        BUSY OFFSET(5) NUMBITS(1),
    ],
    Imr [
        /// Transmit FIFO half-full interrupt
        TXEIM OFFSET(0) NUMBITS(1),
        /// Transmit overflow interrupt
        TXOIM OFFSET(1) NUMBITS(1),
        /// Receive underflow interrupt
        RXUIM OFFSET(2) NUMBITS(1),
        /// Receive overflow interrupt
        RXOIM OFFSET(3) NUMBITS(1),
        /// Receive FIFO half-full interrupt
        RXFIM OFFSET(4) NUMBITS(1),
        /// Multi-master contention interrupt
        MSTIM OFFSET(5) NUMBITS(1),
        /// End of transmit frame interrupt
        FRFIM OFFSET(7) NUMBITS(1),
    ],
    Isr [
        /// TX FIFO half-full
        TXEIS  OFFSET(0) NUMBITS(1),
        /// TX overflow
        TXOIS  OFFSET(1) NUMBITS(1),
        /// RX underflow
        RXUIS  OFFSET(2) NUMBITS(1),
        /// RX overflow
        RXOIS  OFFSET(3) NUMBITS(1),
        /// RX FIFO half-full
        RXFIS  OFFSET(4) NUMBITS(1),
        /// Multi-master contention
        MSTIS  OFFSET(5) NUMBITS(1),
        /// End of transmit frame
        FRFIS  OFFSET(7) NUMBITS(1),
    ],
    Risr [
        /// TX FIFO half-full (raw)
        TXEIR  OFFSET(0) NUMBITS(1),
        /// TX overflow (raw)
        TXOIR  OFFSET(1) NUMBITS(1),
        /// RX underflow (raw)
        RXUIR  OFFSET(2) NUMBITS(1),
        /// RX overflow (raw)
        RXOIR  OFFSET(3) NUMBITS(1),
        /// RX FIFO half-full (raw)
        RXFIR  OFFSET(4) NUMBITS(1),
        /// Multi-master contention (raw)
        MSTIR  OFFSET(5) NUMBITS(1),
        /// End of transmit frame (raw)
        FRFIR  OFFSET(7) NUMBITS(1),
    ],
    Icr [
        /// Dummy field to satisfy register_fields macro (requires >=1 field)
        _ICR_DUMMY OFFSET(0) NUMBITS(1),
    ],
    Version [
        /// Dummy field to satisfy register_fields macro (requires >=1 field)
        _VERSION_DUMMY OFFSET(0) NUMBITS(32),
    ],
    RxSampleDly [
        /// RX sample delay
        RSD OFFSET(0) NUMBITS(8),
    ],
    CsOverride [
        /// CS override enable
        CS_OVERRIDE OFFSET(0) NUMBITS(1),
    ],
    MsccSpiMstSwMode [
        /// MSCC SPI master software mode control
        SW_MODE    OFFSET(0)  NUMBITS(8),
        PIN_ALIAS  OFFSET(8)  NUMBITS(8),
    ],
];

// ---------------------------------------------------------------------------
// Register map layout
// ---------------------------------------------------------------------------
register_structs! {
    pub DwApbSsiRegisters {
        // 0x000: Control Register 0
        (0x000 => ctrlr0: ReadWrite<u32, Ctrlr0::Register>),
        // 0x004: Control Register 1
        (0x004 => ctrlr1: ReadWrite<u32, Ctrlr1::Register>),
        // 0x008: SSI Enable Register
        (0x008 => ssienr: ReadWrite<u32, Ssienr::Register>),
        // 0x00C: Reserved
        (0x00C => _reserved0),
        // 0x010: Slave Enable Register
        (0x010 => ser: ReadWrite<u32, Ser::Register>),
        // 0x014: Baud Rate Select Register
        (0x014 => baudr: ReadWrite<u32, Baudr::Register>),
        // 0x018: TX FIFO Threshold Register
        (0x018 => txftlr: ReadWrite<u32, Txftlr::Register>),
        // 0x01C: RX FIFO Threshold Register
        (0x01C => rxftlr: ReadWrite<u32, Rxftlr::Register>),
        // 0x020: TX FIFO Level Register
        (0x020 => txflr: ReadOnly<u32, Txflr::Register>),
        // 0x024: RX FIFO Level Register
        (0x024 => rxflr: ReadOnly<u32, Rxflr::Register>),
        // 0x028: Status Register
        (0x028 => sr: ReadOnly<u32, Sr::Register>),
        // 0x02C: Interrupt Mask Register
        (0x02C => imr: ReadWrite<u32, Imr::Register>),
        // 0x030: Interrupt Status Register
        (0x030 => isr: ReadOnly<u32, Isr::Register>),
        // 0x034: Raw Interrupt Status Register
        (0x034 => risr: ReadOnly<u32, Risr::Register>),
        // 0x038: Reserved
        (0x038 => _reserved1),
        // 0x048: Interrupt Clear Register
        (0x048 => icr: WriteOnly<u32, Icr::Register>),
        // 0x04C: Reserved
        (0x04C => _reserved2),
        // 0x05C: Version Register
        (0x05C => version: ReadOnly<u32, Version::Register>),
        // 0x060: Reserved
        (0x060 => _reserved3),
        // 0x0F0: RX Sample Delay Register
        (0x0F0 => rx_sample_dly: ReadWrite<u32, RxSampleDly::Register>),
        // 0x0F4: CS Override Register
        (0x0F4 => cs_override: ReadWrite<u32, CsOverride::Register>),
        (0x0F8 => @END),
    }
}

// ---------------------------------------------------------------------------
// MSCC SPI master register map (used by Ocelot/Jaguar2/Sparx5 variants)
// ---------------------------------------------------------------------------
register_structs! {
    pub MsccSpiRegisters {
        // 0x00: MSCC SPI Master Software Mode Register
        (0x00 => mst_sw_mode: ReadWrite<u32, MsccSpiMstSwMode::Register>),
        (0x04 => @END),
    }
}

// ---------------------------------------------------------------------------
// Driver state struct
// ---------------------------------------------------------------------------

/// DW APB SSI private device state, mapped from `struct dw_apb_ssi_priv`.
///
/// Fields correspond to `bind.state` entries:
/// - `dev.base` => `base`: MMIO base address (device virtual address)
pub struct DwApbSsiPriv {
    /// Pointer to the register map (dev->base)
    pub base: &'static DwApbSsiRegisters,
    /// Optional MSCC control register (used by MSCC platform variants)
    pub mscc_base: Option<&'static MsccSpiRegisters>,
    /// RX FIFO threshold current value
    pub rx_threshold: u32,
    /// TX FIFO threshold current value
    pub tx_threshold: u32,
    /// Maximum supported data frame size
    pub max_data_frame_size: u32,
    /// Current operating mode bits
    pub current_mode: u32,
}

impl DwApbSsiPriv {
    /// Constructor: cast a raw base pointer to a reference to the register map.
    ///
    /// `base` is the MMIO virtual address of the DW APB SSI controller.
    pub fn new(base: *mut u8) -> Self {
        let regs: &'static DwApbSsiRegisters =
            unsafe { &*(base as *const DwApbSsiRegisters) };
        Self {
            base: regs,
            mscc_base: None,
            rx_threshold: 0,
            tx_threshold: 0,
            max_data_frame_size: 16,
            current_mode: 0,
        }
    }

    /// Set the optional MSCC register base pointer.
    pub fn set_mscc_base(&mut self, mscc_base: *mut u8) {
        self.mscc_base =
            Some(unsafe { &*(mscc_base as *const MsccSpiRegisters) });
    }

    // -----------------------------------------------------------------------
    // Primitive stubs for MMIO access (bind.primitives)
    // -----------------------------------------------------------------------

    /// Read an 8-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_read8(&self, offset: usize) -> u8 {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *const u8).read_volatile() }
    }

    /// Read a 16-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_read16(&self, offset: usize) -> u16 {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *const u16).read_volatile() }
    }

    /// Read a 32-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_read32(&self, offset: usize) -> u32 {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *const u32).read_volatile() }
    }

    /// Read a 16-bit big-endian MMIO register.
    #[inline]
    fn mmio_read16be(&self, offset: usize) -> u16 {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *const u16).read_volatile().swap_bytes() }
    }

    /// Read a 32-bit big-endian MMIO register.
    #[inline]
    fn mmio_read32be(&self, offset: usize) -> u32 {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *const u32).read_volatile().swap_bytes() }
    }

    /// Write an 8-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_write8(&self, offset: usize, value: u8) {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *mut u8).write_volatile(value) }
    }

    /// Write a 16-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_write16(&self, offset: usize, value: u16) {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *mut u16).write_volatile(value) }
    }

    /// Write a 32-bit MMIO register at the given byte offset from `dev->base`.
    #[inline]
    fn mmio_write32(&self, offset: usize, value: u32) {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *mut u32).write_volatile(value) }
    }

    /// Write a 16-bit big-endian MMIO register.
    #[inline]
    fn mmio_write16be(&self, offset: usize, value: u16) {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *mut u16).write_volatile(value.swap_bytes()) }
    }

    /// Write a 32-bit big-endian MMIO register.
    #[inline]
    fn mmio_write32be(&self, offset: usize, value: u32) {
        let addr = self.base as *const DwApbSsiRegisters as usize + offset;
        unsafe { (addr as *mut u32).write_volatile(value.swap_bytes()) }
    }

    /// Write-1-to-clear an 8-bit MMIO register.
    #[inline]
    fn mmio_write_w1c8(&self, offset: usize, mask: u8) {
        self.mmio_write8(offset, mask);
    }

    /// Write-1-to-clear a 16-bit MMIO register.
    #[inline]
    fn mmio_write_w1c16(&self, offset: usize, mask: u16) {
        self.mmio_write16(offset, mask);
    }

    /// Write-1-to-clear a 32-bit MMIO register.
    #[inline]
    fn mmio_write_w1c32(&self, offset: usize, mask: u32) {
        self.mmio_write32(offset, mask);
    }

    // -----------------------------------------------------------------------
    // Function prototypes (from evidence.functions)
    // Bodies are provided in subsequent generated parts.
    // -----------------------------------------------------------------------

    /// `dw_spi_set_cs` - Set chip select line enable/disable.
    /// Source: spi-dw-core.c:90
    /// Role: write_config
    pub fn dw_spi_set_cs(&self, _enable: u32) {}

    /// `dw_spi_transfer_handler` - Handle SPI data transfer (IRQ context).
    /// Source: spi-dw-core.c:213
    /// Role: interrupt_handler
    pub fn dw_spi_transfer_handler(&self) -> u32 { 0 }

    /// `dw_spi_irq` - Top-level IRQ handler.
    /// Source: spi-dw-core.c:251
    /// Role: interrupt_handler
    pub fn dw_spi_irq(&self, _irq: u32) -> u32 { 0 }

    /// `dw_spi_transfer_one` - Set up and execute a single SPI transfer.
    /// Source: spi-dw-core.c:416
    /// Role: setup_queue
    pub fn dw_spi_transfer_one(&self, _spi: u32, _transfer: u32) -> u32 { 0 }

    /// `dw_spi_handle_err` - Handle SPI controller error.
    /// Source: spi-dw-core.c:478
    /// Role: reset
    pub fn dw_spi_handle_err(&self, _msg: u32) {}

    /// `dw_spi_target_abort` - Abort current SPI target operation.
    /// Source: spi-dw-core.c:484
    /// Role: reset
    pub fn dw_spi_target_abort(&self) -> u32 { 0 }

    /// `dw_spi_exec_mem_op` - Execute a memory operation via SPI.
    /// Source: spi-dw-core.c:675
    /// Role: write_config
    pub fn dw_spi_exec_mem_op(&self, _op: u32) -> u32 { 0 }

    /// `dw_spi_setup` - Set up SPI device clock/mode configuration.
    /// Source: spi-dw-core.c:789
    /// Role: init
    pub fn dw_spi_setup(&self, _spi: u32) -> u32 { 0 }

    /// `dw_spi_cleanup` - Clean up SPI device resources.
    /// Source: spi-dw-core.c:825
    /// Role: remove
    pub fn dw_spi_cleanup(&self, _spi: u32) {}

    /// `dw_spi_mscc_set_cs` - MSCC variant chip select.
    /// Source: spi-dw-mmio.c:77
    /// Role: write_config
    pub fn dw_spi_mscc_set_cs(&self, _enable: u32) {}

    /// `dw_spi_mscc_ocelot_init` - MSCC Ocelot platform init.
    /// Source: spi-dw-mmio.c:128
    /// Role: init
    pub fn dw_spi_mscc_ocelot_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_mscc_jaguar2_init` - MSCC Jaguar2 platform init.
    /// Source: spi-dw-mmio.c:135
    /// Role: init
    pub fn dw_spi_mscc_jaguar2_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_sparx5_set_cs` - Sparx5 variant chip select.
    /// Source: spi-dw-mmio.c:148
    /// Role: write_config
    pub fn dw_spi_sparx5_set_cs(&self, _enable: u32) {}

    /// `dw_spi_mscc_sparx5_init` - Sparx5 platform init.
    /// Source: spi-dw-mmio.c:174
    /// Role: init
    pub fn dw_spi_mscc_sparx5_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_alpine_init` - Alpine platform init.
    /// Source: spi-dw-mmio.c:203
    /// Role: init
    pub fn dw_spi_alpine_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_hssi_init` - HSSI platform init.
    /// Source: spi-dw-mmio.c:219
    /// Role: init
    pub fn dw_spi_hssi_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_intel_init` - Intel platform init.
    /// Source: spi-dw-mmio.c:229
    /// Role: init
    pub fn dw_spi_intel_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_mountevans_imc_init` - Mount Evans IMC platform init.
    /// Source: spi-dw-mmio.c:240
    /// Role: init
    pub fn dw_spi_mountevans_imc_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_canaan_k210_init` - Canaan K210 platform init.
    /// Source: spi-dw-mmio.c:255
    /// Role: init
    pub fn dw_spi_canaan_k210_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_elba_set_cs` - Elba variant chip select.
    /// Source: spi-dw-mmio.c:276
    /// Role: write_config
    pub fn dw_spi_elba_set_cs(&self, _enable: u32) {}

    /// `dw_spi_elba_init` - Elba platform init.
    /// Source: spi-dw-mmio.c:296
    /// Role: init
    pub fn dw_spi_elba_init(&self, _dwsmmio: u32) -> u32 { 0 }

    /// `dw_spi_mmio_probe` - Platform driver probe.
    /// Source: spi-dw-mmio.c:313
    /// Role: probe
    pub fn dw_spi_mmio_probe(&self) -> u32 { 0 }

    /// `dw_spi_mmio_suspend` - Power management suspend.
    /// Source: spi-dw-mmio.c:393
    /// Role: suspend
    pub fn dw_spi_mmio_suspend(&self) -> u32 { 0 }

    /// `dw_spi_mmio_resume` - Power management resume.
    /// Source: spi-dw-mmio.c:410
    /// Role: resume
    pub fn dw_spi_mmio_resume(&self) -> u32 { 0 }

    /// `dw_spi_mmio_remove` - Platform driver remove.
    /// Source: spi-dw-mmio.c:425
    /// Role: remove
    pub fn dw_spi_mmio_remove(&self) {}
}

// ---------------------------------------------------------------------------
// Entry point (userspace / test target)
// ---------------------------------------------------------------------------

/// Userspace / test entry point. Instantiates the device with a zero base
/// address and calls each evidence function in source order with default
/// (zero) arguments. This is only compiled when `#[cfg(test)]` or under a
/// userspace target that includes `std`.
#[cfg(any(test, not(target_os = "none")))]
pub fn main() {
    // Zero-initialized base; in a real deployment this would be the
    // MMIO virtual address from device tree / platform data.
    let base: *mut u8 = 0x1000_0000 as *mut u8;
    let dev = DwApbSsiPriv::new(base);

    // Call each function in evidence order with zero/plausible defaults.
    dev.dw_spi_set_cs(1);
    let _ = dev.dw_spi_transfer_handler();
    let _ = dev.dw_spi_irq(42);
    let _ = dev.dw_spi_transfer_one(0, 0);
    dev.dw_spi_handle_err(0);
    let _ = dev.dw_spi_target_abort();
    let _ = dev.dw_spi_exec_mem_op(0);
    let _ = dev.dw_spi_setup(0);
    dev.dw_spi_cleanup(0);
    dev.dw_spi_mscc_set_cs(1);
    let _ = dev.dw_spi_mscc_ocelot_init(0);
    let _ = dev.dw_spi_mscc_jaguar2_init(0);
    dev.dw_spi_sparx5_set_cs(1);
    let _ = dev.dw_spi_mscc_sparx5_init(0);
    let _ = dev.dw_spi_alpine_init(0);
    let _ = dev.dw_spi_hssi_init(0);
    let _ = dev.dw_spi_intel_init(0);
    let _ = dev.dw_spi_mountevans_imc_init(0);
    let _ = dev.dw_spi_canaan_k210_init(0);
    dev.dw_spi_elba_set_cs(1);
    let _ = dev.dw_spi_elba_init(0);
    let _ = dev.dw_spi_mmio_probe();
    let _ = dev.dw_spi_mmio_suspend();
    let _ = dev.dw_spi_mmio_resume();
    dev.dw_spi_mmio_remove();
}

// ---------------------------------------------------------------------------
// Module init / exit (kernel target)
// ---------------------------------------------------------------------------

/// Module initialization (kernel).
/// Performs platform driver registration. On success returns 0.
#[cfg(target_os = "none")]
pub fn module_init() -> u32 {
    0
}

/// Module exit (kernel).
/// Unregisters the platform driver.
#[cfg(target_os = "none")]
pub fn module_exit() {
}

/* ---- part 01 of 03 ---- */
//! Function bodies for dw-apb-ssi driver modules (Part 1 of 4).
//!
//! This file contains ONLY the method bodies for the six evidence modules:
//!   dw_spi_set_cs, dw_spi_transfer_handler, dw_spi_irq,
//!   dw_spi_transfer_one, dw_spi_handle_err, dw_spi_target_abort
//!
//! The scaffold (struct, registers, constructor, prototypes) is in a
//! separate file and must not be re-emitted.

// ---------------------------------------------------------------------
// Internal transfer state used by dw_spi_transfer_handler and
// dw_spi_transfer_one to model the C `struct dw_spi_priv` runtime fields.
// ---------------------------------------------------------------------

/// Transfer configuration, matching the C `cfg` struct in
/// `dw_spi_transfer_one`.
struct TransferCfg {
    tmode: u32,
    dfs: u32,
    freq: u32,
    ndf: u32,
}

/// Runtime transfer state that the C driver keeps in `struct dw_spi_priv`.
/// These fields are written by `dw_spi_transfer_one` and consumed by
/// `dw_spi_transfer_handler`.
pub struct TransferState {
    pub n_bytes: u32,
    pub reg_io_width: u32,
    pub tx: *mut u8,
    pub tx_len: u32,
    pub rx: *mut u8,
    pub rx_len: u32,
    pub irq: u32,
    pub current_freq: u32,
    pub cur_rx_sample_dly: u32,
    pub dfs_offset: u32,
    pub dma_mapped: u32,
}

impl Default for TransferState {
    fn default() -> Self {
        Self {
            n_bytes: 1,
            reg_io_width: 4,
            tx: core::ptr::null_mut(),
            tx_len: 0,
            rx: core::ptr::null_mut(),
            rx_len: 0,
            irq: 0,
            current_freq: 0,
            cur_rx_sample_dly: 0,
            dfs_offset: 0,
            dma_mapped: 0,
        }
    }
}

impl DwApbSsiPriv {
    // -----------------------------------------------------------------
    // Module: dw_spi_set_cs
    // Source: spi-dw-core.c:90
    // Role: write_config
    // -----------------------------------------------------------------

    /// `dw_spi_set_cs` — Set chip-select line enable/disable.
    ///
    /// RIS ops:
    ///   op_1: IF cs_high == enable → W(B4, DW_SPI_SER) = 1 << cs
    ///   op_2: IF !(cs_high == enable) → W(B4, DW_SPI_SER) = 0
    pub fn dw_spi_set_cs(&self, enable: u32) {
        // cs_high tracks whether CS is active-high. When the CS polarity
        // matches `enable`, assert the slave-select bit for the selected
        // chip; otherwise deassert all slave-select lines.
        let cs_high: u32 = 0;
        let chip_select: u32 = 0;

        if cs_high == enable {
            // op_1: W(B4, dws->regs.DW_SPI_SER) = (0x1 << spi_get_chipselect(spi, 0))
            self.base.ser.set(0x1 << chip_select);
        } else {
            // op_2: W(B4, dws->regs.DW_SPI_SER) = 0x0
            self.base.ser.set(0x0);
        }
    }

    // -----------------------------------------------------------------
    // Module: dw_spi_transfer_handler
    // Source: spi-dw-core.c:213
    // Role: interrupt_handler
    // -----------------------------------------------------------------

    /// `dw_spi_transfer_handler` — Handle SPI data transfer (IRQ context).
    ///
    /// This method reproduces every RIS op in source order:
    ///   op_3  – R(DW_SPI_ISR)
    ///   op_4  – R(DW_SPI_RISR)  [conditional path, always-false guard]
    ///   op_5  – R(DW_SPI_ISR)   [conditional path, always-true guard]
    ///   op_6  – W(DW_SPI_SSIENR) = 0
    ///   op_7  – R(DW_SPI_IMR)
    ///   op_8  – W(DW_SPI_IMR) = new_mask
    ///   op_9  – R(DW_SPI_ICR)
    ///   op_10 – W(DW_SPI_SER) = 0
    ///   op_11 – W(DW_SPI_SSIENR) = 1
    ///   op_12 – STATE(cur_msg->status) = ret
    ///   op_13 – R(DW_SPI_RXFLR)
    ///   op_14/op_15 – R(B2/B4 at offset 0x0) inside RX drain loop
    ///   op_16–op_20 – RX drain: write rx, advance rx ptr, decrement rx_len
    ///   op_21 – R(DW_SPI_IMR) after rx_len==0
    ///   op_22 – W(DW_SPI_IMR) = new_mask
    ///   op_23 – R(DW_SPI_RXFTLR)
    ///   op_24 – W(DW_SPI_RXFTLR) = rx_len - 1
    ///   op_25 – R(DW_SPI_TXFLR)
    ///   op_26–op_33 – TX fill: read tx, write DR, advance tx ptr, dec tx_len
    ///   op_34 – R(DW_SPI_IMR) after tx_len==0
    ///   op_35 – W(DW_SPI_IMR) = new_mask
    pub fn dw_spi_transfer_handler(&self) -> u32 {
        let state = TransferState::default();

        // op_3: irq_status := R(B4, dws->regs.DW_SPI_ISR)
        let irq_status: u32 = self.base.isr.get();

        // dw_spi_check_status(dws, false) — in the evidence the condition
        // simplifies so the inner block is always entered.
        {
            // op_4: ret := R(B4, dws->regs.DW_SPI_RISR)  [guard: 0x0 → false]
            let mut ret: u32 = 0;
            if false {
                ret = self.base.risr.get();
            }
            // op_5: ret := R(B4, dws->regs.DW_SPI_ISR)   [guard: 0x0==0x0 → true]
            if true {
                ret = self.base.isr.get();
            }

            if ret != 0 {
                // op_6: W(B4, dws->regs.DW_SPI_SSIENR) = (0x0 ? 1 : 0)
                self.base.ssienr.set(0x0);

                // op_7: __return_read_0 := R(B4, dws->regs.DW_SPI_IMR)
                let _ = self.base.imr.get();

                // op_8: W(B4, dws->regs.DW_SPI_IMR) = new_mask
                let new_mask: u32 = 0;
                self.base.imr.set(new_mask);

                // op_9: __return_read_0 := R(B4, dws->regs.DW_SPI_ICR)
                //   ICR is WriteOnly in the register map; the C driver reads
                //   the raw 32-bit value for bookkeeping. We model the read
                //   via the low-level mmio_read32 primitive at the ICR offset.
                let _ = self.mmio_read32(0x48);

                // op_10: W(B4, dws->regs.DW_SPI_SER) = 0x0
                self.base.ser.set(0x0);

                // op_11: W(B4, dws->regs.DW_SPI_SSIENR) = (0x1 ? 1 : 0)
                self.base.ssienr.set(0x1);

                // op_12: IF dws->ctlr->cur_msg { STATE(status) := ret }
                //   In no_std we do not model the controller message object;
                //   the state write is a no-op but the conditional is preserved.
            }
        }

        // op_13: __return_read_0 := R(B4, dws->regs.DW_SPI_RXFLR)
        let max: u32 = self.base.rxflr.get();

        // RX drain loop (op_14 – op_20)
        let mut count = max;
        let mut rx_ptr = state.rx;
        let mut rx_len = state.rx_len;
        while {
            count -= 1;
            count < max // post-decrement: runs `max` times
        } {
            // op_14/op_15: read the data register (DR) at offset 0x60
            //   The DW SPI data register sits at a fixed offset; the RIS
            //   evidence shows R(B2, 0x0) for reg_io_width==2 and
            //   R(B4, 0x0) for reg_io_width==4. The offset 0x0 in the RIS
            //   is the data-register offset within the register bank.
            let rxw: u32 = if state.reg_io_width == 0x2 {
                self.mmio_read16(0x60) as u32
            } else if state.reg_io_width == 0x4 {
                self.mmio_read32(0x60)
            } else {
                self.mmio_read32(0x60)
            };

            if !state.rx.is_null() {
                // op_16: OUT(*(u8*)(dws->rx)) := rxw   [n_bytes==1]
                if state.n_bytes == 0x1 {
                    unsafe { *(rx_ptr as *mut u8) = rxw as u8 };
                } else {
                    // op_17: OUT(*(u16*)(dws->rx)) := rxw  [n_bytes==2]
                    if state.n_bytes == 0x2 {
                        unsafe { *(rx_ptr as *mut u16) = rxw as u16 };
                    } else {
                        // op_18: OUT(*(u32*)(dws->rx)) := rxw
                        unsafe { *(rx_ptr as *mut u32) = rxw };
                    }
                }
                // op_19: STATE(dws->rx) := dws->rx + dws->n_bytes
                rx_ptr = unsafe { rx_ptr.add(state.n_bytes as usize) };
            }
            // op_20: STATE(dws->rx_len) := dws->rx_len - 1
            rx_len = rx_len.wrapping_sub(1);
        }

        // op_21/op_22: IF rx_len == 0 { R(IMR); W(IMR) = new_mask }
        if rx_len == 0x0 {
            let _ = self.base.imr.get();
            let new_mask: u32 = 0;
            self.base.imr.set(new_mask);
        } else {
            // op_23: R(DW_SPI_RXFTLR)
            let rxftlr_val = self.base.rxftlr.get();
            // op_24: IF rx_len <= rxftlr_val { W(DW_SPI_RXFTLR) = rx_len - 1 }
            if rx_len <= rxftlr_val {
                self.base.rxftlr.set(rx_len.wrapping_sub(1));
            }
        }

        // op_25: IF irq_status & 0x1 { tx_room := R(DW_SPI_TXFLR) }
        if irq_status & 0x1 != 0 {
            let tx_room: u32 = self.base.txflr.get();

            // op_26: txw := VALUE(0x0)
            let mut txw: u32 = 0x0;
            let mut tx_ptr = state.tx;
            let mut tx_len = state.tx_len;

            let mut tcount = tx_room;
            while {
                tcount -= 1;
                tcount < tx_room
            } {
                // op_27–op_29: read from tx buffer
                if !state.tx.is_null() {
                    if state.n_bytes == 0x1 {
                        // op_27: txw := *(u8*)(dws->tx)
                        txw = unsafe { *(tx_ptr as *const u8) as u32 };
                    } else if state.n_bytes == 0x2 {
                        // op_28: txw := *(u16*)(dws->tx)
                        txw = unsafe { *(tx_ptr as *const u16) as u32 };
                    } else {
                        // op_29: txw := *(u32*)(dws->tx)
                        txw = unsafe { *(tx_ptr as *const u32) };
                    }
                    // op_30: STATE(dws->tx) := dws->tx + dws->n_bytes
                    tx_ptr = unsafe { tx_ptr.add(state.n_bytes as usize) };
                }

                // op_31/op_32: write the data register (DR)
                if state.reg_io_width == 0x2 {
                    self.mmio_write16(0x60, txw as u16);
                } else if state.reg_io_width == 0x4 {
                    self.mmio_write32(0x60, txw);
                }

                // op_33: STATE(dws->tx_len) := dws->tx_len - 1
                tx_len = tx_len.wrapping_sub(1);
            }

            // op_34/op_35: IF tx_len == 0 { R(IMR); W(IMR) = new_mask }
            if tx_len == 0x0 {
                let _ = self.base.imr.get();
                let new_mask: u32 = 0;
                self.base.imr.set(new_mask);
            }
        }

        0
    }

    // -----------------------------------------------------------------
    // Module: dw_spi_irq
    // Source: spi-dw-core.c:251
    // Role: interrupt_handler
    // -----------------------------------------------------------------

    /// `dw_spi_irq` — Top-level IRQ handler.
    ///
    /// RIS ops:
    ///   op_36 – ctlr := VALUE(dev_id)
    ///   op_37 – ctlr := R(B4, DW_SPI_ISR)
    ///   op_38 – R(DW_SPI_IMR)  [when cur_msg == 0]
    ///   op_39 – W(DW_SPI_IMR) = new_mask
    pub fn dw_spi_irq(&self, _irq: u32) -> u32 {
        // op_36: ctlr := VALUE(dev_id)
        //   In C, `dev_id` is the `struct dw_spi *` pointer. We do not
        //   dereference it; the RIS models it as a pure value assignment.

        // op_37: ctlr := R(B4, dws->regs.DW_SPI_ISR)
        //   The C code reuses `ctlr` to hold the ISR value after reading.
        let ctlr: u32 = self.base.isr.get();

        // The real driver checks `ctlr->cur_msg == NULL`; in our model we
        // treat the controller pointer as the ISR value, so we check
        // whether it is zero (no current message).
        if ctlr == 0x0 {
            // op_38: R(DW_SPI_IMR)
            let _ = self.base.imr.get();
            // op_39: W(DW_SPI_IMR) = new_mask
            let new_mask: u32 = 0;
            self.base.imr.set(new_mask);
        }

        0
    }

    // -----------------------------------------------------------------
    // Module: dw_spi_transfer_one
    // Source: spi-dw-core.c:416
    // Role: setup_queue
    // -----------------------------------------------------------------

    /// `dw_spi_transfer_one` — Set up and execute a single SPI transfer.
    ///
    /// RIS ops (op_40 – op_94) reproduced in source order.
    pub fn dw_spi_transfer_one(&self, _spi: u32, _transfer: u32) -> u32 {
        let mut state = TransferState::default();

        // op_40: cfg := { tmode=DW_SPI_CTRLR0_TMOD_TR, dfs=bits_per_word,
        //                  freq=speed_hz }
        let cfg = TransferCfg {
            tmode: 0x0, // DW_SPI_CTRLR0_TMOD_TR
            dfs: 8,
            freq: 0,
            ndf: 0,
        };

        // op_41: STATE(dws->dma_mapped) := 0x0
        state.dma_mapped = 0x0;

        // op_42: STATE(dws->tx) := transfer->tx_buf
        state.tx = 0 as *mut u8;
        // op_43: STATE(dws->tx_len) := transfer->len / dws->n_bytes
        state.tx_len = 0;
        // op_44: STATE(dws->rx) := transfer->rx_buf
        state.rx = 0 as *mut u8;
        // op_45: STATE(dws->rx_len) := dws->tx_len
        state.rx_len = state.tx_len;

        // op_46: W(DW_SPI_SSIENR) = (0x0 ? 1 : 0) → 0
        self.base.ssienr.set(0x0);

        // op_47: cr0 := chip->cr0
        let mut cr0: u32 = 0;
        // op_48: cr0 := cr0 | ((cfg.dfs - 1) << dws->dfs_offset)
        cr0 |= (cfg.dfs.wrapping_sub(0x1)) << state.dfs_offset;

        // op_49: IF dw_spi_ip_is(dws, PSSI) { cr0 |= FIELD_PREP(TMOD_MASK, tmode) }
        let is_pssi = true;
        if is_pssi {
            cr0 |= cfg.tmode << 8; // DW_PSSI_CTRLR0_TMOD_MASK field
        } else {
            // op_50: cr0 |= FIELD_PREP(DW_HSSI_CTRLR0_TMOD_MASK, tmode)
            cr0 |= cfg.tmode << 8;
        }

        // op_51: W(DW_SPI_CTRLR0) = cr0
        self.base.ctrlr0.set(cr0);

        // op_52: IF tmode==3 || tmode==2 { W(DW_SPI_CTRLR1) = ndf?ndf-1:0 }
        if cfg.tmode == 0x3 || cfg.tmode == 0x2 {
            let v = if cfg.ndf != 0 { cfg.ndf.wrapping_sub(0x1) } else { 0x0 };
            self.base.ctrlr1.set(v);
        }

        // op_53: IF current_freq != speed_hz { W(DW_SPI_BAUDR) = clk_div }
        let speed_hz = cfg.freq;
        if state.current_freq != speed_hz {
            let clk_div: u32 = 0;
            self.base.baudr.set(clk_div);
            // op_54: STATE(current_freq) := speed_hz
            state.current_freq = speed_hz;
        }

        // op_55: IF cur_rx_sample_dly != chip->rx_sample_dly { W(RX_SAMPLE_DLY) }
        let chip_rx_sample_dly: u32 = 0;
        if state.cur_rx_sample_dly != chip_rx_sample_dly {
            self.base.rx_sample_dly.set(chip_rx_sample_dly);
            // op_56: STATE(cur_rx_sample_dly) := chip->rx_sample_dly
            state.cur_rx_sample_dly = chip_rx_sample_dly;
        }

        // op_57: STATE(transfer->effective_speed_hz) := dws->current_freq
        //   (state write on the transfer object — no-op here)

        // op_58: R(DW_SPI_IMR)
        let _ = self.base.imr.get();
        // op_59: W(DW_SPI_IMR) = new_mask
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_60: W(DW_SPI_SSIENR) = (0x1 ? 1 : 0) → 1
        self.base.ssienr.set(0x1);

        // op_61–op_88: polling path (when dma_mapped==0 and irq==INVALID)
        if state.dma_mapped == 0x0 {
            if state.irq == 0x80000000 {
                // op_61: delay.unit := 2
                let mut delay_value: u32 = 0;
                let _delay_unit: u32 = 2;

                // do { ... } while (dws->rx_len)
                loop {
                    // op_62: tx_room := R(DW_SPI_TXFLR)
                    let tx_room: u32 = self.base.txflr.get();
                    // op_63: txw := VALUE(0x0)
                    let mut txw: u32 = 0x0;
                    let mut tx_ptr = state.tx;
                    let mut tx_len = state.tx_len;

                    let mut tcount = tx_room;
                    while {
                        tcount -= 1;
                        tcount < tx_room
                    } {
                        // op_64–op_66: read from tx
                        if !state.tx.is_null() {
                            if state.n_bytes == 0x1 {
                                txw = unsafe { *(tx_ptr as *const u8) as u32 };
                            } else if state.n_bytes == 0x2 {
                                txw = unsafe { *(tx_ptr as *const u16) as u32 };
                            } else {
                                txw = unsafe { *(tx_ptr as *const u32) };
                            }
                            tx_ptr = unsafe { tx_ptr.add(state.n_bytes as usize) };
                        }
                        // op_68/op_69: write DR
                        if state.reg_io_width == 0x2 {
                            self.mmio_write16(0x60, txw as u16);
                        } else if state.reg_io_width == 0x4 {
                            self.mmio_write32(0x60, txw);
                        }
                        tx_len = tx_len.wrapping_sub(1);
                    }

                    // op_71: delay.value := nbits * (rx_len - tx_len)
                    let nbits: u32 = 8;
                    delay_value = nbits.wrapping_mul(state.rx_len.wrapping_sub(tx_len));

                    // op_72: R(DW_SPI_RXFLR)
                    let max: u32 = self.base.rxflr.get();
                    let mut rx_ptr = state.rx;
                    let mut rx_len = state.rx_len;

                    let mut rcount = max;
                    while {
                        rcount -= 1;
                        rcount < max
                    } {
                        // op_73/op_74: read DR
                        let rxw: u32 = if state.reg_io_width == 0x2 {
                            self.mmio_read16(0x60) as u32
                        } else if state.reg_io_width == 0x4 {
                            self.mmio_read32(0x60)
                        } else {
                            self.mmio_read32(0x60)
                        };

                        if !state.rx.is_null() {
                            if state.n_bytes == 0x1 {
                                unsafe { *(rx_ptr as *mut u8) = rxw as u8 };
                            } else if state.n_bytes == 0x2 {
                                unsafe { *(rx_ptr as *mut u16) = rxw as u16 };
                            } else {
                                unsafe { *(rx_ptr as *mut u32) = rxw };
                            }
                            rx_ptr = unsafe { rx_ptr.add(state.n_bytes as usize) };
                        }
                        rx_len = rx_len.wrapping_sub(1);
                    }

                    // op_80/op_81: check status
                    let mut ret: u32 = 0;
                    if true {
                        ret = self.base.risr.get();
                    }
                    if false {
                        ret = self.base.isr.get();
                    }

                    if ret != 0 {
                        // op_82: W(DW_SPI_SSIENR) = 0
                        self.base.ssienr.set(0x0);
                        // op_83: R(DW_SPI_IMR)
                        let _ = self.base.imr.get();
                        // op_84: W(DW_SPI_IMR) = new_mask
                        let new_mask2: u32 = 0;
                        self.base.imr.set(new_mask2);
                        // op_85: R(DW_SPI_ICR)
                        let _ = self.mmio_read32(0x48);
                        // op_86: W(DW_SPI_SER) = 0
                        self.base.ser.set(0x0);
                        // op_87: W(DW_SPI_SSIENR) = 1
                        self.base.ssienr.set(0x1);
                        // op_88: STATE(cur_msg->status) = ret
                        break;
                    }

                    if rx_len == 0 {
                        break;
                    }
                    state.rx_len = rx_len;
                    state.tx_len = tx_len;
                }
            }
        }

        // op_89: W(DW_SPI_TXFTLR) = level
        let level: u32 = 0;
        self.base.txftlr.set(level);
        // op_90: W(DW_SPI_RXFTLR) = level - 1
        self.base.rxftlr.set(level.wrapping_sub(0x1));

        // op_91: STATE(dws->transfer_handler) := dw_spi_transfer_handler
        //   (function pointer assignment — no-op in our model)

        // op_92: imask := 0x1|0x2|0x4|0x8|0x10
        let _imask: u32 = 0x1 | 0x2 | 0x4 | 0x8 | 0x10;

        // op_93: R(DW_SPI_IMR)
        let _ = self.base.imr.get();
        // op_94: W(DW_SPI_IMR) = new_mask
        let new_mask_final: u32 = 0;
        self.base.imr.set(new_mask_final);

        0
    }

    // -----------------------------------------------------------------
    // Module: dw_spi_handle_err
    // Source: spi-dw-core.c:478
    // Role: reset
    // -----------------------------------------------------------------

    /// `dw_spi_handle_err` — Handle SPI controller error.
    ///
    /// RIS ops:
    ///   op_95  – W(DW_SPI_SSIENR) = 0   (disable)
    ///   op_96  – R(DW_SPI_IMR)
    ///   op_97  – W(DW_SPI_IMR) = new_mask
    ///   op_98  – R(DW_SPI_ICR)
    ///   op_99  – W(DW_SPI_SER) = 0
    ///   op_100 – W(DW_SPI_SSIENR) = 1   (re-enable)
    pub fn dw_spi_handle_err(&self, _msg: u32) {
        // op_95: W(B4, dws->regs.DW_SPI_SSIENR) = (0x0 ? 1 : 0) → 0
        self.base.ssienr.set(0x0);

        // op_96: __return_read_0 := R(B4, dws->regs.DW_SPI_IMR)
        let _ = self.base.imr.get();

        // op_97: W(B4, dws->regs.DW_SPI_IMR) = new_mask
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_98: __return_read_0 := R(B4, dws->regs.DW_SPI_ICR)
        let _ = self.mmio_read32(0x48);

        // op_99: W(B4, dws->regs.DW_SPI_SER) = 0x0
        self.base.ser.set(0x0);

        // op_100: W(B4, dws->regs.DW_SPI_SSIENR) = (0x1 ? 1 : 0) → 1
        self.base.ssienr.set(0x1);
    }

    // -----------------------------------------------------------------
    // Module: dw_spi_target_abort
    // Source: spi-dw-core.c:484
    // Role: reset
    // -----------------------------------------------------------------

    /// `dw_spi_target_abort` — Abort current SPI target operation.
    ///
    /// RIS ops (identical pattern to dw_spi_handle_err):
    ///   op_101 – W(DW_SPI_SSIENR) = 0
    ///   op_102 – R(DW_SPI_IMR)
    ///   op_103 – W(DW_SPI_IMR) = new_mask
    ///   op_104 – R(DW_SPI_ICR)
    ///   op_105 – W(DW_SPI_SER) = 0
    ///   op_106 – W(DW_SPI_SSIENR) = 1
    pub fn dw_spi_target_abort(&self) -> u32 {
        // op_101: W(B4, dws->regs.DW_SPI_SSIENR) = (0x0 ? 1 : 0) → 0
        self.base.ssienr.set(0x0);

        // op_102: __return_read_0 := R(B4, dws->regs.DW_SPI_IMR)
        let _ = self.base.imr.get();

        // op_103: W(B4, dws->regs.DW_SPI_IMR) = new_mask
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_104: __return_read_0 := R(B4, dws->regs.DW_SPI_ICR)
        let _ = self.mmio_read32(0x48);

        // op_105: W(B4, dws->regs.DW_SPI_SER) = 0x0
        self.base.ser.set(0x0);

        // op_106: W(B4, dws->regs.DW_SPI_SSIENR) = (0x1 ? 1 : 0) → 1
        self.base.ssienr.set(0x1);

        0
    }
}

/* ---- part 02 of 03 ---- */
// ---------------------------------------------------------------------------
// Function bodies for evidence.modules (part 2 of 4)
//
// This file contains ONLY the method bodies for the modules listed in
// evidence.modules, in module order. The scaffold (struct definition,
// register maps, primitive stubs, and prototypes) is in a separate file
// and is NOT re-emitted here.
// ---------------------------------------------------------------------------

// ===================================================================
// Module: dw_spi_exec_mem_op
// Source: spi-dw-core.c:675
// Role: write_config
// ===================================================================
impl DwApbSsiPriv {
    pub fn dw_spi_exec_mem_op_body(&self, op: u32) -> u32 {
        // op encodes direction (bit 0 of op >> 0 is data.dir), len, etc.
        // We use local state to mirror the RIS operations.
        let data_dir: u32 = op & 0x1;
        let len: u32 = op >> 8; // synthetic: upper bits encode length
        let buf_size: u32 = 256; // DW_SPI_BUF_SIZE

        // op_107: IF (len <= DW_SPI_BUF_SIZE) { out := VALUE(dws->buf) }
        let out: *const u8 = if len <= buf_size {
            // dws->buf is an internal buffer; use a placeholder
            core::ptr::null()
        } else {
            core::ptr::null()
        };

        // op_108: STATE(dws->n_bytes) := 0x1
        let mut n_bytes: u32 = 1;

        // op_109: STATE(dws->tx) := out
        let mut tx: *const u8 = out;

        // op_110: STATE(dws->tx_len) := len
        let mut tx_len: u32 = len;

        // op_111/op_112: IF (op->data.dir == 0x1) { rx := op->data.buf.in; rx_len := op->data.nbytes }
        let mut rx: *mut u8 = core::ptr::null_mut();
        let mut rx_len: u32 = 0;
        if data_dir == 0x1 {
            // Conservative: set rx to a placeholder and rx_len to len
            rx = core::ptr::null_mut();
            rx_len = len;
        }

        // op_113/op_114: IF ((op->data.dir == 0x1) == 0x0) { rx := NULL; rx_len := 0x0 }
        if data_dir != 0x1 {
            rx = core::ptr::null_mut();
            rx_len = 0;
        }

        // op_115: STATE(cfg.dfs) := 0x8
        let mut cfg_dfs: u32 = 8;

        // op_116/op_117: IF (op->data.dir == 0x1) { cfg.tmode := 0x3; cfg.ndf := op->data.nbytes }
        let mut cfg_tmode: u32 = 0;
        let mut cfg_ndf: u32 = 0;
        if data_dir == 0x1 {
            cfg_tmode = 3; // DW_SPI_CTRLR0_TMOD_EPROMREAD
            cfg_ndf = len;
        }

        // op_118: IF ((op->data.dir == 0x1) == 0x0) { cfg.tmode := 0x1 }
        if data_dir != 0x1 {
            cfg_tmode = 1; // DW_SPI_CTRLR0_TMOD_TX
        }

        // op_119: W(B4, dws->regs.DW_SPI_SSIENR) = (0x0 ? 0x1 : 0x0)
        // The ternary (0x0 ? 0x1 : 0x0) evaluates to 0x0 (condition is false)
        self.base.ssienr.set(0);

        // op_120: cr0 := VALUE(chip->cr0)
        let chip_cr0: u32 = 0; // placeholder for chip->cr0
        let mut cr0: u32 = chip_cr0;

        // op_121: cr0 := VALUE((cr0 | ((cfg.dfs - 0x1) << dws->dfs_offset)))
        let dfs_offset: u32 = 0; // dws->dfs_offset
        cr0 = cr0 | ((cfg_dfs - 1) << dfs_offset);

        // op_122: IF dw_spi_ip_is(dws, PSSI) { cr0 |= FIELD_PREP(DW_PSSI_CTRLR0_TMOD_MASK, cfg.tmode) }
        // DW_PSSI_CTRLR0_TMOD_MASK = 0x300, shift = 8
        let ip_is_pssi: bool = true; // default PSSI
        if ip_is_pssi {
            cr0 = cr0 | ((cfg_tmode & 0x3) << 8);
        }

        // op_123: IF (dw_spi_ip_is(dws, PSSI) == 0x0) { cr0 |= FIELD_PREP(DW_HSSI_CTRLR0_TMOD_MASK, cfg.tmode) }
        if !ip_is_pssi {
            // DW_HSSI_CTRLR0_TMOD_MASK different offset; use same for now
            cr0 = cr0 | ((cfg_tmode & 0x3) << 8);
        }

        // op_124: W(B4, dws->regs.DW_SPI_CTRLR0) = cr0
        self.base.ctrlr0.set(cr0);

        // op_125: IF ((cfg.tmode == 0x3) || (cfg.tmode == 0x2)) { W(B4, DW_SPI_CTRLR1) = (cfg.ndf ? (cfg.ndf - 0x1) : 0x0) }
        if cfg_tmode == 3 || cfg_tmode == 2 {
            let ctrlr1_val = if cfg_ndf != 0 { cfg_ndf - 1 } else { 0 };
            self.base.ctrlr1.set(ctrlr1_val);
        }

        // op_126/op_127: IF (dws->current_freq != speed_hz) { W(B4, DW_SPI_BAUDR) = clk_div; dws->current_freq := speed_hz }
        let speed_hz: u32 = 0;
        let mut current_freq: u32 = 0;
        let clk_div: u32 = 0;
        if current_freq != speed_hz {
            self.base.baudr.set(clk_div);
            current_freq = speed_hz;
        }

        // op_128/op_129: IF (dws->cur_rx_sample_dly != chip->rx_sample_dly) { W(B4, DW_SPI_RX_SAMPLE_DLY) = chip->rx_sample_dly; dws->cur_rx_sample_dly := chip->rx_sample_dly }
        let chip_rx_sample_dly: u32 = 0;
        let mut cur_rx_sample_dly: u32 = 0;
        if cur_rx_sample_dly != chip_rx_sample_dly {
            self.base.rx_sample_dly.set(chip_rx_sample_dly);
            cur_rx_sample_dly = chip_rx_sample_dly;
        }

        // op_130: __return_read_0 := R(B4, dws->regs.DW_SPI_IMR)
        let _imr_old = self.base.imr.get();

        // op_131: W(B4, dws->regs.DW_SPI_IMR) = new_mask
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_132: W(B4, dws->regs.DW_SPI_SSIENR) = (0x1 ? 0x1 : 0x0)
        // The ternary (0x1 ? 0x1 : 0x0) evaluates to 0x1 (condition is true)
        self.base.ssienr.set(1);

        // op_133: buf := VALUE(dws->tx)
        let mut buf_ptr: *const u8 = tx;

        // op_134/op_135: LOOP while len-- (post-decrement, bounded)
        {
            let mut remaining = len;
            while remaining > 0 {
                remaining -= 1;
                let reg_io_width: u32 = 4; // default
                // op_134: IF (dws->reg_io_width == 0x2) { W(B2, 0x0) = top }
                if reg_io_width == 2 {
                    // dw_write_io_reg with 16-bit: write to DR register
                    self.mmio_write16(0x60, 0); // placeholder value (top)
                }
                // op_135: IF (dws->reg_io_width == 0x4) { W(B4, 0x0) = top }
                if reg_io_width == 4 {
                    self.mmio_write32(0x60, 0); // placeholder value (top)
                }
            }
        }

        // op_136: IF (cs_high == 0x0) { W(B4, DW_SPI_SER) = (0x1 << spi_get_chipselect(mem->spi, 0)) }
        let cs_high: u32 = 0;
        let chip_select: u32 = 0;
        if cs_high == 0 {
            self.base.ser.set(1 << chip_select);
        }
        // op_137: IF ((cs_high == 0x0) == 0x0) { W(B4, DW_SPI_SER) = 0x0 }
        if cs_high != 0 {
            self.base.ser.set(0);
        }

        // op_138-140: LOOP while len (TX FIFO drain)
        {
            let mut tx_len_remaining = tx_len;
            while tx_len_remaining > 0 {
                // op_138: len := R(B4, dws->regs.DW_SPI_TXFLR)
                let txflr = self.base.txflr.get();
                // room = fifo_len - txflr
                let fifo_len: u32 = 32;
                let mut room = if fifo_len > txflr { fifo_len - txflr } else { 0 };
                if room > tx_len_remaining {
                    room = tx_len_remaining;
                }
                // for (room) { dw_write_io_reg(dws, DW_SPI_DR, *buf++) }
                for _ in 0..room {
                    let reg_io_width: u32 = 4;
                    // op_139: IF (dws->reg_io_width == 0x2) { W(B2, 0x0) = top }
                    if reg_io_width == 2 {
                        self.mmio_write16(0x60, 0);
                    }
                    // op_140: IF (dws->reg_io_width == 0x4) { W(B4, 0x0) = top }
                    if reg_io_width == 4 {
                        self.mmio_write32(0x60, 0);
                    }
                    // Advance buf pointer (unsafe in no_std, but matches source)
                    if !buf_ptr.is_null() {
                        buf_ptr = unsafe { buf_ptr.add(1) };
                    }
                }
                tx_len_remaining = if tx_len_remaining > room {
                    tx_len_remaining - room
                } else {
                    0
                };
            }
        }

        // op_141: buf := VALUE(dws->rx)
        let mut rx_buf: *mut u8 = rx;

        // op_142-146: LOOP while len (RX FIFO read)
        {
            let mut rx_remaining = rx_len;
            while rx_remaining > 0 {
                // op_142: len := R(B4, dws->regs.DW_SPI_RXFLR)
                let rxflr = self.base.rxflr.get();
                let mut entries = rxflr;
                if entries > rx_remaining {
                    entries = rx_remaining;
                }
                // op_143: IF (entries == 0x0) { len := R(B4, dws->regs.DW_SPI_RISR) }
                if entries == 0 {
                    let _risr = self.base.risr.get();
                }
                // for (entries) { *buf++ = dw_read_io_reg(dws, DW_SPI_DR) }
                for _ in 0..entries {
                    let reg_io_width: u32 = 4;
                    let mut buffer_read_0: u32 = 0;
                    // op_144: IF (dws->reg_io_width == 0x2) { buffer_read_0 := R(B2, 0x0) }
                    if reg_io_width == 2 {
                        buffer_read_0 = self.mmio_read16(0x60) as u32;
                    }
                    // op_145: IF (dws->reg_io_width == 0x4) { buffer_read_0 := R(B4, 0x0) }
                    if reg_io_width == 4 {
                        buffer_read_0 = self.mmio_read32(0x60);
                    }
                    // op_146: OUT(*buf++) := buffer_read_0
                    if !rx_buf.is_null() {
                        unsafe { *rx_buf = (buffer_read_0 & 0xFF) as u8 };
                        rx_buf = unsafe { rx_buf.add(1) };
                    }
                }
                rx_remaining = if rx_remaining > entries {
                    rx_remaining - entries
                } else {
                    0
                };
            }
        }

        // op_147-160: Error handling / wait for completion
        let mut ret: u32 = 0;
        if ret == 0 {
            // op_147: retry := R(B4, dws->regs.DW_SPI_TXFLR)
            let mut retry = self.base.txflr.get();

            // op_148/op_149: IF (ns <= 0x3e8) { delay.unit := 0x1; delay.value := ns }
            let ns: u32 = 0;
            let mut delay_unit: u32 = 0;
            let mut delay_value: u32 = 0;
            if ns <= 0x3e8 {
                delay_unit = 1;
                delay_value = ns;
            }
            // op_150: IF ((ns <= 0x3e8) == 0x0) { delay.unit := 0x0 }
            if ns > 0x3e8 {
                delay_unit = 0;
            }

            // op_151: LOOP while (dw_spi_ctlr_busy(dws) && retry--) (post-decrement, bounded)
            while retry > 0 {
                // dw_spi_ctlr_busy reads SR and checks BUSY bit
                let sr_val = self.base.sr.get();
                let busy = (sr_val >> 5) & 0x1;
                if busy == 0 {
                    break;
                }
                retry -= 1;
            }

            // op_152-160: IF (ret == 0x0) { ... }
            if ret == 0 {
                // op_152: IF 0x1 { ret := R(B4, dws->regs.DW_SPI_RISR) }
                // The condition is always true (0x1)
                if true {
                    ret = self.base.risr.get();
                }
                // op_153: IF (0x1 == 0x0) { ret := R(B4, dws->regs.DW_SPI_ISR) }
                if false {
                    ret = self.base.isr.get();
                }
                // op_154-160: IF ret { ... error recovery ... }
                if ret != 0 {
                    // op_154: W(B4, DW_SPI_SSIENR) = (0x0 ? 0x1 : 0x0) -> 0x0
                    self.base.ssienr.set(0);
                    // op_155: __return_read_0 := R(B4, DW_SPI_IMR)
                    let _imr_val = self.base.imr.get();
                    // op_156: W(B4, DW_SPI_IMR) = new_mask
                    self.base.imr.set(new_mask);
                    // op_157: __return_read_0 := R(B4, DW_SPI_ICR)
                    let _icr_val = self.base.icr.get();
                    // op_158: W(B4, DW_SPI_SER) = 0x0
                    self.base.ser.set(0);
                    // op_159: W(B4, DW_SPI_SSIENR) = (0x1 ? 0x1 : 0x0) -> 0x1
                    self.base.ssienr.set(1);
                    // op_160: IF dws->ctlr->cur_msg { cur_msg->status := ret }
                    // (skipped: controller state not modeled)
                }
            }
        }

        // op_161: W(B4, dws->regs.DW_SPI_SSIENR) = (0x0 ? 0x1 : 0x0) -> 0x0
        self.base.ssienr.set(0);

        // op_162: IF (cs_high == 0x1) { W(B4, DW_SPI_SER) = (0x1 << spi_get_chipselect(...)) }
        if cs_high == 1 {
            self.base.ser.set(1 << chip_select);
        }
        // op_163: IF ((cs_high == 0x1) == 0x0) { W(B4, DW_SPI_SER) = 0x0 }
        if cs_high != 1 {
            self.base.ser.set(0);
        }

        // op_164: W(B4, dws->regs.DW_SPI_SSIENR) = (0x1 ? 0x1 : 0x0) -> 0x1
        self.base.ssienr.set(1);

        // Suppress unused variable warnings
        let _ = (n_bytes, tx, tx_len, delay_unit, delay_value);

        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_setup
    // Source: spi-dw-core.c:789
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_setup_body(&self, _spi: u32) -> u32 {
        // op_165: IF (chip == 0x0) {
        //   STATE(spi->controller_state) := chip
        //   IF (device_property_read_u32(...) != 0x0) {
        //     rx_sample_dly_ns := VALUE(dws->def_rx_sample_dly_ns)
        //   }
        // }
        // chip is the controller_state; if it's null (0), allocate/initialize
        let chip: u32 = 0; // placeholder: chip is initially null
        if chip == 0 {
            // spi->controller_state = chip (set to a non-null placeholder)
            // In the real driver, this would allocate a chip_data struct.
            // device_property_read_u32 for "rx-sample-delay-ns"
            let prop_found: bool = true; // conservative: property read succeeds
            if !prop_found {
                // rx_sample_dly_ns := dws->def_rx_sample_dly_ns
                let _rx_sample_dly_ns: u32 = 0; // def_rx_sample_dly_ns placeholder
            }
        }
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_cleanup
    // Source: spi-dw-core.c:825
    // Role: remove
    // -------------------------------------------------------------------
    pub fn dw_spi_cleanup_body(&self, _spi: u32) {
        // op_167: STATE(spi->controller_state) := NULL
        // spi->controller_state = NULL
        // (In Rust: no-op since we don't model controller_state as a pointer
        //  stored on the device struct; the operation is represented here.)
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_mscc_set_cs
    // Source: spi-dw-mmio.c:77
    // Role: write_config
    // -------------------------------------------------------------------
    pub fn dw_spi_mscc_set_cs_body(&self, enable: u32) {
        // op_168: dwsmscc := VALUE(dwsmmio->priv)
        // (dwsmmio->priv is the MSCC private data; we use mscc_base)

        let cs: u32 = 0; // spi_get_chipselect(spi, 0) placeholder
        let cs_high: u32 = 0; // placeholder

        // op_169/op_170: IF (cs < 0x4) {
        //   sw_mode := 0x2000
        //   W(B4, dwsmscc->spi_mst.MSCC_SPI_MST_SW_MODE) = ((cs < 0x4) ? 0x2000 : sw_mode)
        // }
        if cs < 4 {
            let sw_mode: u32 = 0x2000;
            let val = if cs < 4 { 0x2000 } else { sw_mode };
            if let Some(mscc) = self.mscc_base {
                mscc.mst_sw_mode.set(val);
            }
        }

        // op_171: IF (cs_high == enable) { W(B4, DW_SPI_SER) = (0x1 << spi_get_chipselect(spi, 0)) }
        if cs_high == enable {
            self.base.ser.set(1 << cs);
        }
        // op_172: IF ((cs_high == enable) == 0x0) { W(B4, DW_SPI_SER) = 0x0 }
        if cs_high != enable {
            self.base.ser.set(0);
        }
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_mscc_ocelot_init
    // Source: spi-dw-mmio.c:128
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_mscc_ocelot_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_173: W(B4, dwsmscc->spi_mst.MSCC_SPI_MST_SW_MODE) = 0x0
        if let Some(mscc) = self.mscc_base {
            mscc.mst_sw_mode.set(0);
        }

        // op_174: TXUPDATE[regmap] dwsmscc->syscon@MSCC_CPU_SYSTEM_CTRL_GENERAL_CTRL
        //   mask=(MSCC_IF_SI_OWNER_MASK << OCELOT_IF_SI_OWNER_OFFSET)
        //   value=(MSCC_IF_SI_OWNER_SIMC << OCELOT_IF_SI_OWNER_OFFSET)
        // MSCC_IF_SI_OWNER_MASK = 0x3, OCELOT_IF_SI_OWNER_OFFSET = 4
        // MSCC_IF_SI_OWNER_SIMC = 0x1
        // regmap_write at offset; we use mmio_write32 as a placeholder
        let mask = 0x3u32 << 4;
        let value = 0x1u32 << 4;
        // syscon regmap is separate; use a conservative mmio write
        // In a real driver, regmap_update_bits would be called.
        // We model it as a write to a placeholder offset.
        self.mmio_write32(0x0, (self.mmio_read32(0x0) & !mask) | (value & mask));

        // op_175: STATE(dwsmmio->dws.set_cs) := dw_spi_mscc_set_cs
        // (function pointer assignment; not directly modeled in Rust)
        // op_176: STATE(dwsmmio->priv) := dwsmscc
        // (private data assignment; not directly modeled)

        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_mscc_jaguar2_init
    // Source: spi-dw-mmio.c:135
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_mscc_jaguar2_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_177: W(B4, dwsmscc->spi_mst.MSCC_SPI_MST_SW_MODE) = 0x0
        if let Some(mscc) = self.mscc_base {
            mscc.mst_sw_mode.set(0);
        }

        // op_178: TXUPDATE[regmap] dwsmscc->syscon@MSCC_CPU_SYSTEM_CTRL_GENERAL_CTRL
        //   mask=(MSCC_IF_SI_OWNER_MASK << JAGUAR2_IF_SI_OWNER_OFFSET)
        //   value=(MSCC_IF_SI_OWNER_SIMC << JAGUAR2_IF_SI_OWNER_OFFSET)
        // JAGUAR2_IF_SI_OWNER_OFFSET = 6
        let mask = 0x3u32 << 6;
        let value = 0x1u32 << 6;
        self.mmio_write32(0x0, (self.mmio_read32(0x0) & !mask) | (value & mask));

        // op_179: STATE(dwsmmio->dws.set_cs) := dw_spi_mscc_set_cs
        // op_180: STATE(dwsmmio->priv) := dwsmscc

        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_sparx5_set_cs
    // Source: spi-dw-mmio.c:148
    // Role: write_config
    // -------------------------------------------------------------------
    pub fn dw_spi_sparx5_set_cs_body(&self, enable: u32) {
        // op_181: dwsmscc := VALUE(dwsmmio->priv)

        let cs: u32 = 0; // spi_get_chipselect(spi, 0) placeholder
        let cs_high: u32 = 0; // placeholder

        // op_182: IF (enable == 0x0) {
        //   TXWRITE[regmap] syscon@SPARX5_FORCE_ENA {1}
        //   TXWRITE[regmap] syscon@SPARX5_FORCE_VAL { (1 << cs) ^ 0xFFFFFFFF }
        // }
        if enable == 0 {
            // SPARX5_FORCE_ENA: write 1
            self.mmio_write32(0x0, 1);
            // SPARX5_FORCE_VAL: (1 << cs) ^ 0xFFFFFFFF
            let force_val = (1u32 << cs) ^ 0xFFFFFFFF;
            self.mmio_write32(0x4, force_val);
        }

        // op_184: IF ((enable == 0x0) == 0x0) {
        //   TXWRITE[regmap] syscon@SPARX5_FORCE_VAL { 0 ^ 0xFFFFFFFF = 0xFFFFFFFF }
        //   TXWRITE[regmap] syscon@SPARX5_FORCE_ENA {0}
        // }
        if enable != 0 {
            // SPARX5_FORCE_VAL: 0 ^ 0xFFFFFFFF = 0xFFFFFFFF
            self.mmio_write32(0x4, 0xFFFFFFFF);
            // SPARX5_FORCE_ENA: 0
            self.mmio_write32(0x0, 0);
        }

        // op_186: IF (cs_high == enable) { W(B4, DW_SPI_SER) = (0x1 << cs) }
        if cs_high == enable {
            self.base.ser.set(1 << cs);
        }
        // op_187: IF ((cs_high == enable) == 0x0) { W(B4, DW_SPI_SER) = 0x0 }
        if cs_high != enable {
            self.base.ser.set(0);
        }
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_mscc_sparx5_init
    // Source: spi-dw-mmio.c:174
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_mscc_sparx5_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_188: syscon_name := "microchip,sparx5-cpu-syscon"
        let _syscon_name: &str = "microchip,sparx5-cpu-syscon";

        // op_189: dev := &pdev->dev
        // (device pointer; not directly modeled)

        // op_190: STATE(dwsmmio->dws.set_cs) := dw_spi_sparx5_set_cs
        // op_191: STATE(dwsmmio->priv) := dwsmscc

        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_alpine_init
    // Source: spi-dw-mmio.c:203
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_alpine_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_192: STATE(dwsmmio->dws.caps) := 0x1
        // DW_SPI_CAP_EXT_SLOT is bit 0
        // (caps field not on our struct; represented as a no-op state change)
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_hssi_init
    // Source: spi-dw-mmio.c:219
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_hssi_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_193: STATE(dwsmmio->dws.ip) := 0x1
        // DW_HSSI_IP = 1
        // (ip field not on our struct; represented as a no-op state change)
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_intel_init
    // Source: spi-dw-mmio.c:229
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_intel_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_194: STATE(dwsmmio->dws.ip) := 0x1
        // DW_HSSI_IP = 1 (Intel uses HSSI interface)
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_mountevans_imc_init
    // Source: spi-dw-mmio.c:240
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_mountevans_imc_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_195: STATE(dwsmmio->dws.fifo_len) := 0x1f
        // fifo_len = 31
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_canaan_k210_init
    // Source: spi-dw-mmio.c:255
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_canaan_k210_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_196: STATE(dwsmmio->dws.fifo_len) := 0x1f
        // fifo_len = 31
        0
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_elba_set_cs
    // Source: spi-dw-mmio.c:276
    // Role: write_config
    // -------------------------------------------------------------------
    pub fn dw_spi_elba_set_cs_body(&self, enable: u32) {
        // op_197: syscon := VALUE(dwsmmio->priv)

        let cs: u32 = 0; // spi_get_chipselect(spi, 0) placeholder
        let cs_high: u32 = 0; // placeholder

        // op_198: IF (cs < 0x2) {
        //   TXUPDATE[regmap] syscon@ELBA_SPICS_REG
        //     mask=ELBA_SPICS_MASK(spi_get_chipselect(spi, 0))
        //     value=ELBA_SPICS_SET(spi_get_chipselect(spi, 0), enable)
        // }
        // ELBA_SPICS_REG offset, mask and set are platform-specific.
        // ELBA_SPICS_MASK(cs) = 0x1 << (cs + 4)
        // ELBA_SPICS_SET(cs, enable) = (enable ? 0 : (0x1 << (cs + 4)))
        if cs < 2 {
            let mask = 0x1u32 << (cs + 4);
            let value = if enable != 0 { 0 } else { 0x1u32 << (cs + 4) };
            self.mmio_write32(
                0x0,
                (self.mmio_read32(0x0) & !mask) | (value & mask),
            );
        }

        // op_199: IF (cs_high == enable) { W(B4, DW_SPI_SER) = (0x1 << cs) }
        if cs_high == enable {
            self.base.ser.set(1 << cs);
        }
        // op_200: IF ((cs_high == enable) == 0x0) { W(B4, DW_SPI_SER) = 0x0 }
        if cs_high != enable {
            self.base.ser.set(0);
        }
    }

    // -------------------------------------------------------------------
    // Module: dw_spi_elba_init
    // Source: spi-dw-mmio.c:296
    // Role: init
    // -------------------------------------------------------------------
    pub fn dw_spi_elba_init_body(&self, _dwsmmio: u32) -> u32 {
        // op_201: STATE(dwsmmio->priv) := syscon
        // op_202: STATE(dwsmmio->dws.set_cs) := dw_spi_elba_set_cs
        0
    }
}

/* ---- part 03 of 03 ---- */
//! Method bodies for dw_spi_mmio_probe, dw_spi_mmio_suspend,
//! dw_spi_mmio_resume, dw_spi_mmio_remove.
//!
//! These are impl blocks that augment the `DwApbSsiPriv` struct defined
//! in the scaffold.  Each method reproduces the RIS module operations in
//! source order using tock-registers accessors.

use crate::DwApbSsiPriv;

impl DwApbSsiPriv {
    // -------------------------------------------------------------------
    // dw_spi_mmio_probe  (spi-dw-mmio.c:313, role: probe)
    // -------------------------------------------------------------------

    /// `dw_spi_mmio_probe` – Platform driver probe.
    ///
    /// Reproduces every RIS op in `module dw_spi_mmio_probe` in source
    /// order.  State writes that correspond to Linux framework bookkeeping
    /// (ctlr->mode_bits, ctlr->bus_num, etc.) are modelled as local
    /// assignments because those subsystems are not present in this
    /// no_std driver.  The MMIO accesses, however, are faithfully emitted
    /// using tock-registers.
    pub fn dw_spi_mmio_probe(&self) -> u32 {
        // op_203: dws := VALUE(&dwsmmio->dws)
        // In this model `self` *is* the dws/private state, so nothing to dereference.

        // op_204: STATE(dws->paddr) := mem->start
        // op_205: STATE(dws->bus_num) := pdev->id
        // These are platform-resource lookups; modelled as no-ops here.

        // op_206: IF device_property_read_u32("reg-io-width", &dws->reg_io_width)
        //         { dws->reg_io_width := 4 }
        let _reg_io_width: u32 = 4;

        // op_207–op_208: STATE(dws->ctlr) := ctlr; STATE(dws->dma_addr) := paddr + 0x60
        // Framework bookkeeping; skipped in the no_std model.

        // op_209: W(B4, DW_SPI_SSIENR) = (0x0 ? 1 : 0) → write 0  (disable SSI)
        self.base.ssienr.set(0);

        // op_210: __return_read_0 := R(B4, DW_SPI_IMR)
        let _imr_val = self.base.imr.get();

        // op_211: W(B4, DW_SPI_IMR) = new_mask
        // `new_mask` is computed in the original code from the interrupt
        // enable bits; we model it as 0 (disable all interrupts on probe).
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_212: __return_read_0 := R(B4, DW_SPI_ICR)
        // ICR is WriteOnly in the register map, so reading is not modelled;
        // the original code does `dw_readl(icr)` which we approximate as 0.
        let _icr_val: u32 = 0;

        // op_213: W(B4, DW_SPI_SER) = 0  (clear slave selects)
        self.base.ser.set(0);

        // op_214: W(B4, DW_SPI_SSIENR) = (0x1 ? 1 : 0) → write 1  (enable SSI)
        self.base.ssienr.set(1);

        // op_215: IF (dws->ver == 0) { dws->ver := R(B4, DW_SPI_VERSION) }
        // We use a local to model dws->ver since it lives in the private struct
        // which is not mutable through &self.  In a full driver this would be
        // &mut self.
        // Modelled as: read version (always 0 in this abstraction).
        let _ver: u32 = self.base.version.get();

        // op_216: IF spi_controller_is_target(dws->ctlr) { dws->num_cs := 1 }
        // Not a target in this model.

        // op_217–op_219: IF !target && dws->num_cs == 0
        //   W(DW_SPI_SER) = 0xffff; ser := R(DW_SPI_SER); W(DW_SPI_SER) = 0
        {
            let num_cs: u32 = 0; // modelled
            let is_target: bool = false;
            if !is_target && num_cs == 0 {
                self.base.ser.set(0xffff);
                let _ser = self.base.ser.get();
                self.base.ser.set(0);
            }
        }

        // op_220–op_223: IF dws->fifo_len == 0 → detect FIFO depth
        {
            let mut fifo_len: u32 = 0;
            if fifo_len == 0 {
                let mut fifo: u32 = 1;
                while fifo < 0x100 {
                    // op_220: W(DW_SPI_TXFTLR) = fifo
                    self.base.txftlr.set(fifo);
                    // op_221: __return_read_0 := R(DW_SPI_TXFTLR)
                    let _readback = self.base.txftlr.get();
                    fifo += 1;
                }
                // op_222: W(DW_SPI_TXFTLR) = 0
                self.base.txftlr.set(0);
                // op_223: fifo_len := (fifo == 1) ? 0 : fifo
                fifo_len = if fifo == 1 { 0 } else { fifo };
            }
            // In the full driver this would be stored: self.fifo_len = fifo_len;
        }

        // op_224–op_230: IF dw_spi_ip_is(dws, PSSI) { … }
        {
            let is_pssi: bool = true; // modelled: default IP type is PSSI
            if is_pssi {
                // op_224: __return_read_0 := R(DW_SPI_CTRLR0)
                let _cr0_read1 = self.base.ctrlr0.get();
                // op_225: W(DW_SPI_SSIENR) = 0  (disable)
                self.base.ssienr.set(0);
                // op_226: W(DW_SPI_CTRLR0) = 0xffffffff
                self.base.ctrlr0.set(0xffff_ffff);
                // op_227: cr0 := R(DW_SPI_CTRLR0)
                let cr0 = self.base.ctrlr0.get();
                // op_228: W(DW_SPI_CTRLR0) = tmp  (restore original value)
                let tmp: u32 = _cr0_read1; // restore saved value
                self.base.ctrlr0.set(tmp);
                // op_229: W(DW_SPI_SSIENR) = 1  (enable)
                self.base.ssienr.set(1);
                // op_230: IF (cr0 & DW_PSSI_CTRLR0_DFS_MASK) == 0 { caps |= 0x2 }
                let dw_pssi_ctrlr0_dfs_mask: u32 = 0x3; // 4-bit DFS field
                if (cr0 & dw_pssi_ctrlr0_dfs_mask) == 0 {
                    // STATE(dws->caps) |= 0x2
                    // modelled as local
                }
            }
        }

        // op_231: IF !dw_spi_ip_is(dws, PSSI) { caps |= 0x2 }
        {
            let is_pssi: bool = true;
            if !is_pssi {
                // caps |= 0x2
            }
        }

        // op_232: IF (dws->caps & 0x1) { W(DW_SPI_CS_OVERRIDE) = 0xf }
        {
            let caps: u32 = 0; // modelled
            if (caps & 0x1) != 0 {
                self.base.cs_override.set(0xf);
            }
        }

        // op_233–op_236: mem_ops setup (framework bookkeeping, skipped)
        // op_237–op_255: ctlr field assignments (framework, skipped)
        // op_256–op_257: debugfs regset (framework, skipped)

        // op_258: IF 0x0 { … W(DW_SPI_SSIENR) = 0 … }
        // Dead branch (condition is false); not emitted.

        0 // success
    }

    // -------------------------------------------------------------------
    // dw_spi_mmio_suspend  (spi-dw-mmio.c:393, role: suspend)
    // -------------------------------------------------------------------

    /// `dw_spi_mmio_suspend` – Power management suspend.
    ///
    /// Two MMIO writes: disable the SSI and clear the baud rate.
    pub fn dw_spi_mmio_suspend(&self) -> u32 {
        // op_259: W(B4, DW_SPI_SSIENR) = (0x0 ? 1 : 0) → write 0
        self.base.ssienr.set(0);
        // op_260: W(B4, DW_SPI_BAUDR) = 0
        self.base.baudr.set(0);
        0
    }

    // -------------------------------------------------------------------
    // dw_spi_mmio_resume  (spi-dw-mmio.c:410, role: resume)
    // -------------------------------------------------------------------

    /// `dw_spi_mmio_resume` – Power management resume.
    ///
    /// Re-initialises the controller, mirroring the probe init path.
    pub fn dw_spi_mmio_resume(&self) -> u32 {
        // op_261: W(DW_SPI_SSIENR) = 0  (disable)
        self.base.ssienr.set(0);

        // op_262: __return_read_0 := R(DW_SPI_IMR)
        let _imr_val = self.base.imr.get();

        // op_263: W(DW_SPI_IMR) = new_mask
        let new_mask: u32 = 0;
        self.base.imr.set(new_mask);

        // op_264: __return_read_0 := R(DW_SPI_ICR)
        // ICR is WriteOnly; modelled as 0.
        let _icr_val: u32 = 0;

        // op_265: W(DW_SPI_SER) = 0
        self.base.ser.set(0);

        // op_266: W(DW_SPI_SSIENR) = 1  (enable)
        self.base.ssienr.set(1);

        // op_267: IF (dws->ver == 0) { dws->ver := R(DW_SPI_VERSION) }
        let _ver: u32 = self.base.version.get();

        // op_268: IF spi_controller_is_target { num_cs := 1 }
        // Not target in this model.

        // op_269–op_271: IF !target && num_cs == 0
        {
            let num_cs: u32 = 0;
            let is_target: bool = false;
            if !is_target && num_cs == 0 {
                self.base.ser.set(0xffff);
                let _ser = self.base.ser.get();
                self.base.ser.set(0);
            }
        }

        // op_272–op_275: IF fifo_len == 0 → detect FIFO depth
        {
            let mut fifo_len: u32 = 0;
            if fifo_len == 0 {
                let mut fifo: u32 = 1;
                while fifo < 0x100 {
                    self.base.txftlr.set(fifo);
                    let _readback = self.base.txftlr.get();
                    fifo += 1;
                }
                self.base.txftlr.set(0);
                fifo_len = if fifo == 1 { 0 } else { fifo };
            }
        }

        // op_276–op_282: IF dw_spi_ip_is(PSSI)
        {
            let is_pssi: bool = true;
            if is_pssi {
                let _cr0_read1 = self.base.ctrlr0.get();
                self.base.ssienr.set(0);
                self.base.ctrlr0.set(0xffff_ffff);
                let cr0 = self.base.ctrlr0.get();
                let tmp: u32 = _cr0_read1;
                self.base.ctrlr0.set(tmp);
                self.base.ssienr.set(1);
                let dw_pssi_ctrlr0_dfs_mask: u32 = 0x3;
                if (cr0 & dw_pssi_ctrlr0_dfs_mask) == 0 {
                    // caps |= 0x2
                }
            }
        }

        // op_283: IF !dw_spi_ip_is(PSSI) { caps |= 0x2 }
        {
            let is_pssi: bool = true;
            if !is_pssi {
                // caps |= 0x2
            }
        }

        // op_284: IF (caps & 0x1) { W(DW_SPI_CS_OVERRIDE) = 0xf }
        {
            let caps: u32 = 0;
            if (caps & 0x1) != 0 {
                self.base.cs_override.set(0xf);
            }
        }

        0
    }

    // -------------------------------------------------------------------
    // dw_spi_mmio_remove  (spi-dw-mmio.c:425, role: remove)
    // -------------------------------------------------------------------

    /// `dw_spi_mmio_remove` – Platform driver remove.
    ///
    /// Disables the SSI and clears the baud rate, identical to suspend.
    pub fn dw_spi_mmio_remove(&self) {
        // op_285: W(B4, DW_SPI_SSIENR) = (0x0 ? 1 : 0) → write 0
        self.base.ssienr.set(0);
        // op_286: W(B4, DW_SPI_BAUDR) = 0
        self.base.baudr.set(0);
    }
}