#ifndef REHARNESS_SPI-DW-CORE_LINUX_H
#define REHARNESS_SPI-DW-CORE_LINUX_H

/* Auto-generated by LLM (reharness) */
#include <linux/module.h>
#include <linux/io.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/miscdevice.h>
#include <linux/slab.h>
#include <linux/err.h>
#include <linux/platform_device.h>

static void __iomem *__rh_mmio_base;
#define RH_SET_BASE(b) do { __rh_mmio_base = (b); pr_info("[rhbase] %px\n", (void __iomem *)(b)); } while (0)
#define RH_TRACE_FN(name) pr_info("[rhfn] %s\n", (name))
#define rh_off(p) ((unsigned long)((const void __iomem *)(p) - __rh_mmio_base))
#undef readl
#define readl(p) ({ u32 __v = __raw_readl(p); pr_info("[rh] R 0x%lx 0x%x\n", rh_off(p), __v); __v; })
#undef writel
#define writel(v,p) ({ pr_info("[rh] W 0x%lx 0x%x\n", rh_off(p), (u32)(v)); __raw_writel((v),(p)); })

#define DW_SPI_CTRLR0 0
#define DW_SPI_CTRLR1 4
#define DW_SPI_SER 16
#define DW_SPI_TXFTLR 24
#define DW_SPI_RXFTLR 28
#define DW_SPI_TXFLR 32
#define DW_SPI_RXFLR 36
#define DW_SPI_SR 40
#define DW_SPI_ISR 48
#define DW_SPI_RISR 52
#define DW_SPI_VERSION 92
#define DW_SPI_RX_SAMPLE_DLY 240
#define DW_SPI_CS_OVERRIDE 244

#define DW_SPI_CAP_CS_OVERRIDE 1
#define DW_SPI_CTRLR0_TMOD_EPROMREAD 3
#define DW_SPI_CTRLR0_TMOD_RO 2

struct dw_spi_chip_data {
	u32 cr0;
	u32 rx_sample_dly;
};

#endif /* REHARNESS_SPI-DW-CORE_LINUX_H */
