#ifndef REHARNESS_DW-APB-SSI_LINUX_H
#define REHARNESS_DW-APB-SSI_LINUX_H

/* Auto-generated by LLM (reharness) */
#include <linux/module.h>
#include <linux/io.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/miscdevice.h>
#include <linux/slab.h>
#include <linux/err.h>
#include <linux/platform_device.h>

/* Constants */
#define DW_HSSI_102A 825242154
#define DW_HSSI_CTRLR0_MST 2147483648
#define DW_HSSI_CTRLR0_SCPHA 256
#define DW_HSSI_CTRLR0_SCPOL 512
#define DW_HSSI_CTRLR0_SRL 8192
#define DW_HSSI_ID 1
#define DW_PSSI_CTRLR0_CFS 4096
#define DW_PSSI_CTRLR0_SCPHA 64
#define DW_PSSI_CTRLR0_SCPOL 128
#define DW_PSSI_CTRLR0_SLV_OE 1024
#define DW_PSSI_CTRLR0_SRL 2048
#define DW_PSSI_ID 0
#define DW_SPI_BAUDR 20
#define DW_SPI_CAP_CS_OVERRIDE 1
#define DW_SPI_CAP_DFS32 2
#define DW_SPI_CS_OVERRIDE 244
#define DW_SPI_CTRLR0_FRF_MOTO_SPI 0
#define DW_SPI_CTRLR0_FRF_NS_MICROWIRE 2
#define DW_SPI_CTRLR0_FRF_RESV 3
#define DW_SPI_CTRLR0_FRF_TI_SSP 1
#define DW_SPI_CTRLR0_TMOD_EPROMREAD 3
#define DW_SPI_CTRLR0_TMOD_RO 2
#define DW_SPI_CTRLR0_TMOD_TO 1
#define DW_SPI_CTRLR0_TMOD_TR 0
#define DW_SPI_CTRLR1 4
#define DW_SPI_DMACR 76
#define DW_SPI_DMACR_RDMAE 1
#define DW_SPI_DMACR_TDMAE 2
#define DW_SPI_DMARDLR 84
#define DW_SPI_DMATDLR 80
#define DW_SPI_DR 96
#define DW_SPI_IDR 88
#define DW_SPI_INT_MSTI 32
#define DW_SPI_INT_RXFI 16
#define DW_SPI_INT_RXOI 8
#define DW_SPI_INT_RXUI 4
#define DW_SPI_INT_TXEI 1
#define DW_SPI_INT_TXOI 2
#define DW_SPI_MSTICR 68
#define DW_SPI_MWCR 12
#define DW_SPI_RXOICR 60
#define DW_SPI_RXUICR 64
#define DW_SPI_RX_SAMPLE_DLY 240
#define DW_SPI_SR_BUSY 1
#define DW_SPI_SR_DCOL 64
#define DW_SPI_SR_RF_FULL 16
#define DW_SPI_SR_RF_NOT_EMPT 8
#define DW_SPI_SR_TF_EMPT 4
#define DW_SPI_SR_TF_NOT_FULL 2
#define DW_SPI_SR_TX_ERR 32
#define DW_SPI_SSIENR 8
#define DW_SPI_TXOICR 56
#define DW_SPI_WAIT_RETRIES 5
#define ELBA_SPICS_REG 9320
#define IRQ_NOTCONNECTED 2147483648
#define JAGUAR2_IF_SI_OWNER_OFFSET 6
#define MSCC_CPU_SYSTEM_CTRL_GENERAL_CTRL 36
#define MSCC_IF_SI_OWNER_SIBM 1
#define MSCC_IF_SI_OWNER_SIMC 2
#define MSCC_IF_SI_OWNER_SISL 0
#define MSCC_SPI_MST_SW_MODE_SW_PIN_CTRL_MODE 8192
#define OCELOT_IF_SI_OWNER_OFFSET 4
#define SPARX5_FORCE_ENA 164
#define SPARX5_FORCE_VAL 168

/* Registers */
#define DW_SPI_CTRLR0 0
#define DW_SPI_ICR 72
#define DW_SPI_IMR 44
#define DW_SPI_ISR 48
#define DW_SPI_RISR 52
#define DW_SPI_RXFLR 36
#define DW_SPI_RXFTLR 28
#define DW_SPI_SER 16
#define DW_SPI_SR 40
#define DW_SPI_TXFLR 32
#define DW_SPI_TXFTLR 24
#define DW_SPI_VERSION 92
#define MSCC_SPI_MST_SW_MODE 20

/* MMIO trace instrumentation */
static void __iomem *__rh_mmio_base;
#define RH_SET_BASE(b) do { __rh_mmio_base = (b); pr_info("[rhbase] %px\n", (void __iomem *)(b)); } while (0)
#define RH_TRACE_FN(name) pr_info("[rhfn] %s\n", (name))
#define rh_off(p) ((unsigned long)((const void __iomem *)(p) - __rh_mmio_base))
#undef readl
#define readl(p) ({ u32 __v = __raw_readl(p); pr_info("[rh] R 0x%lx 0x%x\n", rh_off(p), __v); __v; })
#undef writel
#define writel(v,p) ({ pr_info("[rh] W 0x%lx 0x%x\n", rh_off(p), (u32)(v)); __raw_writel((v),(p)); })

struct dw_apb_ssi_priv {
	void __iomem *base;
	struct miscdevice misc;
	struct device *dev;
};

#endif /* REHARNESS_DW-APB-SSI_LINUX_H */
