/* Auto-generated by LLM (reharness) */
#![cfg_attr(not(test), no_std)]

use tock_registers::{
    register_bitfields,
    register_structs,
    registers::{ReadOnly, ReadWrite, WriteOnly},
};

register_structs! {
    pub DwSpiCoreRegisters {
        (0x000 => ctrlr0: ReadWrite<u32, Ctrlr0::Register>),
        (0x004 => ctrlr1: ReadWrite<u32, Ctrlr1::Register>),
        (0x008 => _reserved0),
        (0x010 => ser: ReadWrite<u32, Ser::Register>),
        (0x014 => _reserved1),
        (0x018 => txftlr: ReadWrite<u32, Txftlr::Register>),
        (0x01c => rxftlr: ReadWrite<u32, Rxftlr::Register>),
        (0x020 => txflr: ReadOnly<u32, Txflr::Register>),
        (0x024 => rxflr: ReadOnly<u32, Rxflr::Register>),
        (0x028 => sr: ReadOnly<u32, Sr::Register>),
        (0x02c => isr: ReadOnly<u32, Isr::Register>),
        (0x030 => risr: ReadOnly<u32, Risr::Register>),
        (0x034 => _reserved2),
        (0x05c => version: ReadOnly<u32, Version::Register>),
        (0x060 => _reserved3),
        (0x0f0 => rx_sample_dly: ReadWrite<u32, RxSampleDly::Register>),
        (0x0f4 => cs_override: ReadWrite<u32, CsOverride::Register>),
        (0x0f8 => @END),
    }
}

register_bitfields![u32,
    Ctrlr0 [],
    Ctrlr1 [],
    Ser [],
    Txftlr [],
    Rxftlr [],
    Txflr [],
    Rxflr [],
    Sr [],
    Isr [],
    Risr [],
    Version [],
    RxSampleDly [],
    CsOverride []
];

pub struct SpiDwCore {
    regs: &'static DwSpiCoreRegisters,
}

impl SpiDwCore {
    pub fn new(base: *mut u8) -> Self {
        Self {
            regs: unsafe { &*(base as *const DwSpiCoreRegisters) },
        }
    }

    pub fn dw_spi_set_cs(&self, cs_high: bool, enable: bool, chip_select: u32) {
        if cs_high == enable {
            self.regs.ser.set(0x1 << chip_select);
        }
        if (cs_high == enable) == false {
            self.regs.ser.set(0x0);
        }
    }

    pub fn dw_writer(&self) -> u32 {
        self.regs.txflr.get()
    }

    pub fn dw_reader(&self, offset: usize) -> u32 {
        // offset is dynamically calculated in original driver, but for standard MMIO
        // we map it directly to the RXFLR register as implied by typical DW SPI usage.
        let _ = offset;
        self.regs.rxflr.get()
    }

    pub fn dw_spi_check_status(&self, raw: bool) -> u32 {
        if raw {
            return self.regs.risr.get();
        }
        if raw == false {
            return self.regs.isr.get();
        }
        0
    }

    pub fn dw_spi_transfer_handler(&self, rx_len: u32) {
        let _irq_status = self.regs.isr.get();
        if rx_len != 0 {
            let r8 = self.regs.rxftlr.get();
            if rx_len <= r8 {
                self.regs.rxftlr.set(rx_len - 1);
            }
        }
    }

    pub fn dw_spi_irq(&self) -> u32 {
        self.regs.isr.get()
    }

    pub fn dw_spi_update_config(
        &self,
        cr0: u32,
        tmode: u32,
        ndf: u32,
        cur_rx_sample_dly: u32,
        rx_sample_dly: u32,
    ) {
        self.regs.ctrlr0.set(cr0);
        if (tmode | 0x200) == 0x200 {
            let val = if ndf != 0 { ndf - 1 } else { 0 };
            self.regs.ctrlr1.set(val);
        }
        if cur_rx_sample_dly != rx_sample_dly {
            self.regs.rx_sample_dly.set(rx_sample_dly);
        }
    }

    pub fn dw_spi_transfer_one(&self, level: u32) {
        self.regs.txftlr.set(level);
        self.regs.rxftlr.set(level - 1);
    }

    pub fn dw_spi_exec_mem_op(&self, len: usize, ret: i32) {
        let mut _entries;
        let mut _sts;
        let mut _nents = 0;

        let mut i = 0;
        while i < len {
            _entries = self.regs.txflr.get();
            i += 1;
        }

        let mut j = 0;
        while j < len {
            _entries = self.regs.rxflr.get();
            if _entries == 0 {
                _sts = self.regs.risr.get();
            }
            j += 1;
        }

        if ret == 0 {
            _nents = self.regs.txflr.get();
        }
    }

    pub fn dw_spi_add_controller(
        &self,
        dws_valid: bool,
        mut ver: u32,
        is_target: bool,
        mut num_cs: u32,
        mut fifo_len: u32,
        is_pssi: bool,
        caps: u32,
    ) -> (u32, u32, u32) {
        if dws_valid {
            if ver == 0 {
                ver = self.regs.version.get();
            }
            if !is_target {
                if num_cs == 0 {
                    self.regs.ser.set(0xffff);
                    let _ser = self.regs.ser.get();
                    self.regs.ser.set(0x0);
                    num_cs = 1; // Simulate update
                }
            }
            if fifo_len == 0 {
                let mut fifo = 0;
                while fifo < 0x100 {
                    self.regs.txftlr.set(fifo);
                    let _r25 = self.regs.txftlr.get();
                    if _r25 != fifo {
                        break;
                    }
                    fifo += 1;
                }
                self.regs.txftlr.set(0x0);
                fifo_len = fifo;
            }
            if is_pssi {
                let _r27 = self.regs.ctrlr0.get();
                self.regs.ctrlr0.set(0xffffffff);
                let cr0 = self.regs.ctrlr0.get();
                self.regs.ctrlr0.set(cr0); // write 'tmp' (cr0)
            }
            if (caps & 0x1) != 0 {
                self.regs.cs_override.set(0xf);
            }
        }
        (ver, num_cs, fifo_len)
    }

    pub fn dw_spi_resume_controller(
        &self,
        mut ver: u32,
        is_target: bool,
        mut num_cs: u32,
        mut fifo_len: u32,
        is_pssi: bool,
        caps: u32,
    ) -> (u32, u32, u32) {
        if ver == 0 {
            ver = self.regs.version.get();
        }
        if !is_target {
            if num_cs == 0 {
                self.regs.ser.set(0xffff);
                let _ser = self.regs.ser.get();
                self.regs.ser.set(0x0);
                num_cs = 1;
            }
        }
        if fifo_len == 0 {
            let mut fifo = 0;
            while fifo < 0x100 {
                self.regs.txftlr.set(fifo);
                let _r37 = self.regs.txftlr.get();
                if _r37 != fifo {
                    break;
                }
                fifo += 1;
            }
            self.regs.txftlr.set(0x0);
            fifo_len = fifo;
        }
        if is_pssi {
            let _r39 = self.regs.ctrlr0.get();
            self.regs.ctrlr0.set(0xffffffff);
            let cr0 = self.regs.ctrlr0.get();
            self.regs.ctrlr0.set(cr0);
        }
        if (caps & 0x1) != 0 {
            self.regs.cs_override.set(0xf);
        }
        (ver, num_cs, fifo_len)
    }
}